/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainScreenUI;

import Dialog.LoginDialog;
import Dialog.RegisterDialog;
import ContentUI.DetailConference;
import Business.AccountBus;
import Business.UserBus;
import ContentUI.ConferenceUI;
import ContentUI.Home;
import ContentUI.ListConference;
import ContentUI.Statistic;
import ContentUI.UserInformation;
import ContentUI.UsersUI;
import DAO.AccountDao;
import POJO.Account;
import POJO.Conference;
import POJO.User;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    final static private Color deufault = new Color(58, 1, 108);
    final static private Color colorCliked = new Color(84, 3, 156);
    final static private Color colorMoved = new Color(74, 2, 137);
    final static private Color colorMoved_2 = new Color(220, 220, 255);

    private User user = null;

    private Home mainHome;
    private ListConference listConference;
    private ConferenceUI conferenceUI;
    private UsersUI usersUI;
    private Statistic statistic;
    private UserInformation userInformation;

    private static MainScreen mainScreen = null;

    public Home getMainHome() {
        return mainHome;
    }

    public ListConference getListConference() {
        return listConference;
    }

    public Statistic getStatistic() {
        return statistic;
    }

    public UserInformation getUserInformation() {
        return userInformation;
    }

    public UsersUI getUsersUI() {
        return usersUI;
    }

    public ConferenceUI getConferenceUI() {
        return conferenceUI;
    }

    public static MainScreen getInstance() {
        if (mainScreen == null) {
            mainScreen = new MainScreen();
            return mainScreen;
        } else {
            return mainScreen;
        }
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
        if (user != null) {
            jName.setText("Hello " + user.getName());
            jStatisticPnl.setVisible(true);
            jInformationPnl.setVisible(true);
            jLogin.setText("Log out");

            if (user.getIsAdmin() == 1) {
                jConferencesPnl.setVisible(true);
                jUsersPnl.setVisible(true);
            }
        } else {
            mainHome = new Home();
            listConference = new ListConference();
            conferenceUI = new ConferenceUI();
            usersUI = new UsersUI();
            statistic = new Statistic();
            userInformation = new UserInformation();

            setColorClicked(jHomePnl);
            resetColorUnClicked(jListConferencePnl);
            resetColorUnClicked(jStatisticPnl);
            resetColorUnClicked(jConferencesPnl);
            resetColorUnClicked(jUsersPnl);
            resetColorUnClicked(jInformationPnl);

            jCardLayout.removeAll();
            jCardLayout.add(mainHome);
            jCardLayout.repaint();
            jCardLayout.revalidate();
        }
    }

    public MainScreen() {
        initComponents();
        mainHome = new Home();
        listConference = new ListConference();
        conferenceUI = new ConferenceUI();
        usersUI = new UsersUI();
        statistic = new Statistic();
        userInformation = new UserInformation();

        jUsersPnl.setVisible(false);
        jInformationPnl.setVisible(false);
        jConferencesPnl.setVisible(false);
        jStatisticPnl.setVisible(false);

        setColorClicked(jHomePnl);
        resetColorUnClicked(jListConferencePnl);
        resetColorUnClicked(jStatisticPnl);
        resetColorUnClicked(jInformationPnl);
        resetColorUnClicked(jConferencesPnl);
        resetColorUnClicked(jUsersPnl);

        jCardLayout.removeAll();
        jCardLayout.add(mainHome);
        jCardLayout.repaint();
        jCardLayout.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainScreen = new javax.swing.JPanel();
        jCardLayout = new javax.swing.JPanel();
        jUsers = new javax.swing.JPanel();
        jMenu = new javax.swing.JPanel();
        jOptionMenu = new javax.swing.JPanel();
        jMenubtn = new javax.swing.JPanel();
        jButtonMenu = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jHomePnl = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jListConferencePnl = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jStatisticPnl = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jInformationPnl = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jConferencesPnl = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jUsersPnl = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSpace = new javax.swing.JPanel();
        jHeader = new javax.swing.JPanel();
        jLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLog = new javax.swing.JPanel();
        jExitPnl = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jName = new javax.swing.JLabel();
        jLoginbtn = new javax.swing.JPanel();
        jLogin = new javax.swing.JLabel();
        jFooter = new javax.swing.JPanel();
        jAuthor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1400, 700));
        setSize(new java.awt.Dimension(1400, 700));

        jMainScreen.setBackground(new java.awt.Color(58, 1, 108));
        jMainScreen.setLayout(new java.awt.BorderLayout());

        jCardLayout.setLayout(new java.awt.CardLayout());

        jUsers.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jUsersLayout = new javax.swing.GroupLayout(jUsers);
        jUsers.setLayout(jUsersLayout);
        jUsersLayout.setHorizontalGroup(
            jUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jUsersLayout.setVerticalGroup(
            jUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jCardLayout.add(jUsers, "card5");

        jMainScreen.add(jCardLayout, java.awt.BorderLayout.CENTER);

        jMenu.setBackground(new java.awt.Color(0, 153, 0));
        jMenu.setPreferredSize(new java.awt.Dimension(200, 590));
        jMenu.setLayout(new java.awt.BorderLayout());

        jOptionMenu.setBackground(new java.awt.Color(58, 1, 108));
        jOptionMenu.setPreferredSize(new java.awt.Dimension(200, 400));
        jOptionMenu.setLayout(new java.awt.GridLayout(0, 1));

        jMenubtn.setBackground(new java.awt.Color(58, 1, 108));
        jMenubtn.setLayout(new java.awt.BorderLayout());

        jButtonMenu.setBackground(new java.awt.Color(58, 1, 108));
        jButtonMenu.setPreferredSize(new java.awt.Dimension(50, 0));
        jButtonMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonMenuMouseMoved(evt);
            }
        });
        jButtonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMenuMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonMenuMouseReleased(evt);
            }
        });
        jButtonMenu.setLayout(new java.awt.BorderLayout());

        jLabel13.setBackground(new java.awt.Color(58, 1, 108));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/List-icon.png"))); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(50, 0));
        jButtonMenu.add(jLabel13, java.awt.BorderLayout.WEST);

        jMenubtn.add(jButtonMenu, java.awt.BorderLayout.EAST);

        jOptionMenu.add(jMenubtn);

        jHomePnl.setBackground(new java.awt.Color(58, 1, 108));
        jHomePnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jHomePnlMouseMoved(evt);
            }
        });
        jHomePnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jHomePnlMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jHomePnlMousePressed(evt);
            }
        });
        jHomePnl.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home.png"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 24));
        jHomePnl.add(jLabel4, java.awt.BorderLayout.WEST);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Home");
        jHomePnl.add(jLabel8, java.awt.BorderLayout.CENTER);

        jOptionMenu.add(jHomePnl);

        jListConferencePnl.setBackground(new java.awt.Color(58, 1, 108));
        jListConferencePnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jListConferencePnlMouseMoved(evt);
            }
        });
        jListConferencePnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jListConferencePnlMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jListConferencePnlMouseReleased(evt);
            }
        });
        jListConferencePnl.setLayout(new java.awt.BorderLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Purchase-Order-icon.png"))); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(50, 24));
        jListConferencePnl.add(jLabel11, java.awt.BorderLayout.WEST);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Conference List");
        jListConferencePnl.add(jLabel12, java.awt.BorderLayout.CENTER);

        jOptionMenu.add(jListConferencePnl);

        jStatisticPnl.setBackground(new java.awt.Color(58, 1, 108));
        jStatisticPnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jStatisticPnlMouseMoved(evt);
            }
        });
        jStatisticPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jStatisticPnlMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jStatisticPnlMouseReleased(evt);
            }
        });
        jStatisticPnl.setLayout(new java.awt.BorderLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Call-Statistics-icon.png"))); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 24));
        jStatisticPnl.add(jLabel7, java.awt.BorderLayout.WEST);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Statistics");
        jStatisticPnl.add(jLabel5, java.awt.BorderLayout.CENTER);

        jOptionMenu.add(jStatisticPnl);

        jInformationPnl.setBackground(new java.awt.Color(58, 1, 108));
        jInformationPnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jInformationPnlMouseMoved(evt);
            }
        });
        jInformationPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jInformationPnlMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jInformationPnlMouseReleased(evt);
            }
        });
        jInformationPnl.setLayout(new java.awt.BorderLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Male-User-icon-2.png"))); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(50, 24));
        jInformationPnl.add(jLabel14, java.awt.BorderLayout.WEST);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Information");
        jInformationPnl.add(jLabel6, java.awt.BorderLayout.CENTER);

        jOptionMenu.add(jInformationPnl);

        jConferencesPnl.setBackground(new java.awt.Color(58, 1, 108));
        jConferencesPnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jConferencesPnlMouseMoved(evt);
            }
        });
        jConferencesPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jConferencesPnlMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jConferencesPnlMouseReleased(evt);
            }
        });
        jConferencesPnl.setLayout(new java.awt.BorderLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Conference-icon.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(50, 24));
        jConferencesPnl.add(jLabel9, java.awt.BorderLayout.WEST);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Conferences");
        jConferencesPnl.add(jLabel10, java.awt.BorderLayout.CENTER);

        jOptionMenu.add(jConferencesPnl);

        jUsersPnl.setBackground(new java.awt.Color(58, 1, 108));
        jUsersPnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jUsersPnlMouseMoved(evt);
            }
        });
        jUsersPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jUsersPnlMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jUsersPnlMouseReleased(evt);
            }
        });
        jUsersPnl.setLayout(new java.awt.BorderLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/User-Menu-Female-icon.png"))); // NOI18N
        jLabel18.setPreferredSize(new java.awt.Dimension(50, 24));
        jUsersPnl.add(jLabel18, java.awt.BorderLayout.LINE_START);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Users");
        jUsersPnl.add(jLabel19, java.awt.BorderLayout.CENTER);

        jOptionMenu.add(jUsersPnl);

        jMenu.add(jOptionMenu, java.awt.BorderLayout.NORTH);

        jSpace.setBackground(new java.awt.Color(58, 1, 108));
        jSpace.setPreferredSize(new java.awt.Dimension(200, 290));

        javax.swing.GroupLayout jSpaceLayout = new javax.swing.GroupLayout(jSpace);
        jSpace.setLayout(jSpaceLayout);
        jSpaceLayout.setHorizontalGroup(
            jSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jSpaceLayout.setVerticalGroup(
            jSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu.add(jSpace, java.awt.BorderLayout.CENTER);

        jMainScreen.add(jMenu, java.awt.BorderLayout.WEST);

        getContentPane().add(jMainScreen, java.awt.BorderLayout.CENTER);

        jHeader.setBackground(new java.awt.Color(58, 1, 108));
        jHeader.setPreferredSize(new java.awt.Dimension(1200, 80));
        jHeader.setLayout(new java.awt.BorderLayout());

        jLogo.setBackground(new java.awt.Color(58, 1, 108));
        jLogo.setPreferredSize(new java.awt.Dimension(200, 100));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Brush Script Std", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONFERENCE");

        javax.swing.GroupLayout jLogoLayout = new javax.swing.GroupLayout(jLogo);
        jLogo.setLayout(jLogoLayout);
        jLogoLayout.setHorizontalGroup(
            jLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLogoLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jLogoLayout.setVerticalGroup(
            jLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLogoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jHeader.add(jLogo, java.awt.BorderLayout.WEST);

        jLog.setLayout(new java.awt.BorderLayout());

        jExitPnl.setBackground(new java.awt.Color(58, 1, 108));
        jExitPnl.setPreferredSize(new java.awt.Dimension(40, 30));
        jExitPnl.setLayout(new java.awt.BorderLayout());
        jLog.add(jExitPnl, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(new java.awt.Color(58, 1, 108));
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 40));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        jName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jName.setForeground(new java.awt.Color(255, 255, 255));
        jName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jName.setPreferredSize(new java.awt.Dimension(600, 40));
        jPanel4.add(jName);

        jLoginbtn.setBackground(new java.awt.Color(58, 1, 108));
        jLoginbtn.setPreferredSize(new java.awt.Dimension(150, 50));
        jLoginbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLoginbtnMouseMoved(evt);
            }
        });
        jLoginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLoginbtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLoginbtnMouseReleased(evt);
            }
        });
        jLoginbtn.setLayout(new java.awt.BorderLayout());

        jLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/login_24px.png"))); // NOI18N
        jLogin.setText("Log in");
        jLoginbtn.add(jLogin, java.awt.BorderLayout.CENTER);

        jPanel4.add(jLoginbtn);

        jLog.add(jPanel4, java.awt.BorderLayout.CENTER);

        jHeader.add(jLog, java.awt.BorderLayout.CENTER);

        getContentPane().add(jHeader, java.awt.BorderLayout.NORTH);

        jFooter.setBackground(new java.awt.Color(58, 1, 108));
        jFooter.setPreferredSize(new java.awt.Dimension(1200, 30));
        jFooter.setLayout(new java.awt.BorderLayout());

        jAuthor.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jAuthor.setForeground(new java.awt.Color(255, 255, 255));
        jAuthor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jAuthor.setText("@Author: Lê Tấn Hưng @MSSV: 1712479   ");
        jAuthor.setPreferredSize(new java.awt.Dimension(300, 13));
        jFooter.add(jAuthor, java.awt.BorderLayout.EAST);

        getContentPane().add(jFooter, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jHomePnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomePnlMousePressed
//         TODO add your handling code here:
        setColorClicked(jHomePnl);
        resetColorUnClicked(jListConferencePnl);
        resetColorUnClicked(jStatisticPnl);
        resetColorUnClicked(jInformationPnl);
        resetColorUnClicked(jConferencesPnl);
        resetColorUnClicked(jUsersPnl);

        jCardLayout.removeAll();
        jCardLayout.add(mainHome);
        jCardLayout.repaint();
        jCardLayout.revalidate();
    }//GEN-LAST:event_jHomePnlMousePressed

    private void jStatisticPnlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStatisticPnlMouseReleased
        // TODO add your handling code here:
        statistic.resetData();

        setColorClicked(jStatisticPnl);
        resetColorUnClicked(jHomePnl);
        resetColorUnClicked(jListConferencePnl);
        resetColorUnClicked(jInformationPnl);
        resetColorUnClicked(jConferencesPnl);
        resetColorUnClicked(jUsersPnl);

        jCardLayout.removeAll();
        jCardLayout.add(statistic);
        jCardLayout.repaint();
        jCardLayout.revalidate();
    }//GEN-LAST:event_jStatisticPnlMouseReleased

    private void jConferencesPnlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jConferencesPnlMouseReleased
        //  TODO add your handling code here
        conferenceUI.resetData();

        setColorClicked(jConferencesPnl);
        resetColorUnClicked(jHomePnl);
        resetColorUnClicked(jListConferencePnl);
        resetColorUnClicked(jStatisticPnl);
        resetColorUnClicked(jInformationPnl);
        resetColorUnClicked(jUsersPnl);

        jCardLayout.removeAll();
        jCardLayout.add(conferenceUI);
        jCardLayout.repaint();
        jCardLayout.revalidate();
    }//GEN-LAST:event_jConferencesPnlMouseReleased

    private void jUsersPnlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUsersPnlMouseReleased
        // TODO add your handling code here:
        usersUI.resetData();

        setColorClicked(jUsersPnl);
        resetColorUnClicked(jHomePnl);
        resetColorUnClicked(jListConferencePnl);
        resetColorUnClicked(jStatisticPnl);
        resetColorUnClicked(jInformationPnl);
        resetColorUnClicked(jConferencesPnl);

        jCardLayout.removeAll();
        jCardLayout.add(usersUI);
        jCardLayout.repaint();
        jCardLayout.revalidate();
    }//GEN-LAST:event_jUsersPnlMouseReleased

    private void jHomePnlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomePnlMouseMoved
        // TODO add your handling code here:
        if (jHomePnl.getBackground() != colorCliked)
            setColorMoved(jHomePnl);
    }//GEN-LAST:event_jHomePnlMouseMoved

    private void jHomePnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomePnlMouseExited
        // TODO add your handling code here:
        if (jHomePnl.getBackground() != colorCliked)
            resetColorUnClicked(jHomePnl);
    }//GEN-LAST:event_jHomePnlMouseExited

    private void jStatisticPnlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStatisticPnlMouseMoved
        // TODO add your handling code here:
        if (jStatisticPnl.getBackground() != colorCliked)
            setColorMoved(jStatisticPnl);
    }//GEN-LAST:event_jStatisticPnlMouseMoved

    private void jStatisticPnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStatisticPnlMouseExited
        // TODO add your handling code here:
        if (jStatisticPnl.getBackground() != colorCliked)
            resetColorUnClicked(jStatisticPnl);
    }//GEN-LAST:event_jStatisticPnlMouseExited

    private void jConferencesPnlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jConferencesPnlMouseMoved
        // TODO add your handling code here:
        if (jConferencesPnl.getBackground() != colorCliked)
            setColorMoved(jConferencesPnl);
    }//GEN-LAST:event_jConferencesPnlMouseMoved

    private void jConferencesPnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jConferencesPnlMouseExited
        // TODO add your handling code here:
        if (jConferencesPnl.getBackground() != colorCliked)
            resetColorUnClicked(jConferencesPnl);
    }//GEN-LAST:event_jConferencesPnlMouseExited

    private void jUsersPnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUsersPnlMouseExited
        // TODO add your handling code here:
        if (jUsersPnl.getBackground() != colorCliked)
            resetColorUnClicked(jUsersPnl);
    }//GEN-LAST:event_jUsersPnlMouseExited

    private void jUsersPnlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUsersPnlMouseMoved
        // TODO add your handling code here:    
        if (jUsersPnl.getBackground() != colorCliked)
            setColorMoved(jUsersPnl);
    }//GEN-LAST:event_jUsersPnlMouseMoved

    private void jButtonMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenuMouseExited
        // TODO add your handling code here:
        resetColorUnClicked(jButtonMenu);
    }//GEN-LAST:event_jButtonMenuMouseExited

    private void jButtonMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenuMouseMoved
        // TODO add your handling code here:
        setColorMoved(jButtonMenu);
    }//GEN-LAST:event_jButtonMenuMouseMoved

    private void jButtonMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenuMouseReleased
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (jMenu.getWidth() == 200) {
            Thread thread = new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 200; i >= 50; i = i - 1) {
                            Thread.sleep(1);
                            jMenu.setSize(i, 640);
                        }

                        jMenu.setPreferredSize(new Dimension(50, 0));
                        revalidate();

                    } catch (Exception e) {
                    }
                }
            });
            thread.start();
        }

        if (jMenu.getWidth() == 50) {
            Thread thread = new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 50; i <= 200; i = i + 1) {
                            Thread.sleep(1);
                            jMenu.setSize(i, 640);
                        }

                        jMenu.setPreferredSize(new Dimension(200, 0));
                        repaint();
                        revalidate();
                    } catch (Exception e) {
                    }
                }
            });
            thread.start();
        }
    }//GEN-LAST:event_jButtonMenuMouseReleased

    private void jLoginbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginbtnMouseExited
        // TODO add your handling code here:
        resetColorUnClicked(jLoginbtn);
    }//GEN-LAST:event_jLoginbtnMouseExited

    private void jLoginbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginbtnMouseMoved
        // TODO add your handling code here:   
        setColorMoved(jLoginbtn);
    }//GEN-LAST:event_jLoginbtnMouseMoved

    private void jLoginbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginbtnMouseReleased
        // TODO add your handling code here:
        if (jLogin.getText().compareTo("Log in") == 0)
            new LoginDialog(this, true).setVisible(true);
        else {
            setUser(null);
            jLogin.setText("Log in");
            jName.setText("");
            jStatisticPnl.setVisible(false);
            jInformationPnl.setVisible(false);
            jConferencesPnl.setVisible(false);
            jUsersPnl.setVisible(false);
            JOptionPane.showMessageDialog(this, "Log out success");
        }
    }//GEN-LAST:event_jLoginbtnMouseReleased

    private void jListConferencePnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListConferencePnlMouseExited
        // TODO add your handling code here:
        if (jListConferencePnl.getBackground() != colorCliked)
            resetColorUnClicked(jListConferencePnl);
    }//GEN-LAST:event_jListConferencePnlMouseExited

    private void jListConferencePnlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListConferencePnlMouseMoved
        // TODO add your handling code here:
        if (jListConferencePnl.getBackground() != colorCliked)
            setColorMoved(jListConferencePnl);
    }//GEN-LAST:event_jListConferencePnlMouseMoved

    private void jListConferencePnlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListConferencePnlMouseReleased
        // TODO add your handling code here:
        listConference.resetData();

        setColorClicked(jListConferencePnl);
        resetColorUnClicked(jHomePnl);
        resetColorUnClicked(jStatisticPnl);
        resetColorUnClicked(jInformationPnl);
        resetColorUnClicked(jConferencesPnl);
        resetColorUnClicked(jUsersPnl);

        jCardLayout.removeAll();
        jCardLayout.add(listConference);
        jCardLayout.repaint();
        jCardLayout.revalidate();
    }//GEN-LAST:event_jListConferencePnlMouseReleased

    private void jInformationPnlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInformationPnlMouseMoved
        // TODO add your handling code here:
        if (jInformationPnl.getBackground() != colorCliked)
            setColorMoved(jInformationPnl);
    }//GEN-LAST:event_jInformationPnlMouseMoved

    private void jInformationPnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInformationPnlMouseExited
        // TODO add your handling code here:
        if (jInformationPnl.getBackground() != colorCliked)
            resetColorUnClicked(jInformationPnl);
    }//GEN-LAST:event_jInformationPnlMouseExited

    private void jInformationPnlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInformationPnlMouseReleased
        // TODO add your handling code here:
        userInformation.resetData();

        setColorClicked(jInformationPnl);
        resetColorUnClicked(jHomePnl);
        resetColorUnClicked(jListConferencePnl);
        resetColorUnClicked(jStatisticPnl);
        resetColorUnClicked(jConferencesPnl);
        resetColorUnClicked(jUsersPnl);

        jCardLayout.removeAll();
        jCardLayout.add(userInformation);
        jCardLayout.repaint();
        jCardLayout.revalidate();


    }//GEN-LAST:event_jInformationPnlMouseReleased

    void setColorClicked(JPanel jp) {
        jp.setBackground(colorCliked);

    }

    void setColorMoved(JPanel jp) {
        jp.setBackground(colorMoved);
    }

    void resetColorUnClicked(JPanel jp) {
        jp.setBackground(deufault);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAuthor;
    private javax.swing.JPanel jButtonMenu;
    private javax.swing.JPanel jCardLayout;
    private javax.swing.JPanel jConferencesPnl;
    private javax.swing.JPanel jExitPnl;
    private javax.swing.JPanel jFooter;
    private javax.swing.JPanel jHeader;
    private javax.swing.JPanel jHomePnl;
    private javax.swing.JPanel jInformationPnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jListConferencePnl;
    private javax.swing.JPanel jLog;
    private javax.swing.JLabel jLogin;
    private javax.swing.JPanel jLoginbtn;
    private javax.swing.JPanel jLogo;
    private javax.swing.JPanel jMainScreen;
    private javax.swing.JPanel jMenu;
    private javax.swing.JPanel jMenubtn;
    private javax.swing.JLabel jName;
    private javax.swing.JPanel jOptionMenu;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jSpace;
    private javax.swing.JPanel jStatisticPnl;
    private javax.swing.JPanel jUsers;
    private javax.swing.JPanel jUsersPnl;
    // End of variables declaration//GEN-END:variables

    public void changeDetailConference(Conference conference, int type) {
        jCardLayout.removeAll();
        jCardLayout.add(new DetailConference(conference, this, type));
        jCardLayout.repaint();
        jCardLayout.revalidate();
    }

    public void backToListConference() {
        listConference.resetData();

        jCardLayout.removeAll();
        jCardLayout.add(listConference);
        jCardLayout.repaint();
        jCardLayout.revalidate();
    }

    public void backToStatistic() {
        statistic.resetData();

        jCardLayout.removeAll();
        jCardLayout.add(statistic);
        jCardLayout.repaint();
        jCardLayout.revalidate();
    }

    public void backToConferenceUI() {
        conferenceUI.resetData();

        jCardLayout.removeAll();
        jCardLayout.add(conferenceUI);
        jCardLayout.repaint();
        jCardLayout.revalidate();
    }

    public void backToUserUI() {

        jCardLayout.removeAll();
        jCardLayout.add(usersUI);
        jCardLayout.repaint();
        jCardLayout.revalidate();
    }

    public void login() {
        new LoginDialog(this, true).setVisible(true);
    }

    public void register() {
        new RegisterDialog(this, true).setVisible(true);
    }

    public void resetStatistic() {
        statistic = statistic.cloneS();
        statistic.resetData();
        jCardLayout.removeAll();
        jCardLayout.add(statistic);
        jCardLayout.repaint();
        jCardLayout.revalidate();
    }

    public void resetConferenceUI() {
        conferenceUI = conferenceUI.cloneS();
        conferenceUI.resetData();
        jCardLayout.removeAll();
        jCardLayout.add(conferenceUI);
        jCardLayout.repaint();
        jCardLayout.revalidate();
    }

}
