/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainScreenUI;

import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author ADMIN
 */
public class NewConference extends javax.swing.JFrame {

    /**
     * Creates new form NewConference
     */
    public NewConference() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jInformationConference = new javax.swing.JPanel();
        jName = new javax.swing.JLabel();
        jNameText = new javax.swing.JTextField();
        jImage = new javax.swing.JLabel();
        jImageText = new javax.swing.JTextField();
        jAddImagebtn = new javax.swing.JButton();
        jPlace = new javax.swing.JLabel();
        jPlaceChooser = new javax.swing.JComboBox<>();
        jAddNewPlace = new javax.swing.JButton();
        jDate = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jStart = new javax.swing.JLabel();
        Date dateStart = new Date(0);

        SpinnerDateModel smStart = new SpinnerDateModel(dateStart, null, null, Calendar.HOUR_OF_DAY);
        jStartTime = new javax.swing.JSpinner(smStart);
        jEnd = new javax.swing.JLabel();
        Date dateEnd = new Date(0);

        SpinnerDateModel smEnd = new SpinnerDateModel(dateEnd, null, null, Calendar.HOUR_OF_DAY);
        jEndTime = new javax.swing.JSpinner(smEnd);
        jLabel1 = new javax.swing.JLabel();
        jDetail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jFooter = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 650));
        setPreferredSize(new java.awt.Dimension(650, 700));

        jInformationConference.setPreferredSize(new java.awt.Dimension(600, 600));
        jInformationConference.setLayout(new java.awt.GridBagLayout());

        jName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jName.setText("Name");
        jName.setPreferredSize(new java.awt.Dimension(100, 50));
        jInformationConference.add(jName, new java.awt.GridBagConstraints());

        jNameText.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jNameText.setText("Name Text");
        jNameText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jNameText.setPreferredSize(new java.awt.Dimension(400, 40));
        jInformationConference.add(jNameText, new java.awt.GridBagConstraints());

        jImage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jImage.setText("Image");
        jImage.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jInformationConference.add(jImage, gridBagConstraints);

        jImageText.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jImageText.setText("LinkImage");
        jImageText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jImageText.setPreferredSize(new java.awt.Dimension(400, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jInformationConference.add(jImageText, gridBagConstraints);

        jAddImagebtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jAddImagebtn.setText("ADD");
        jAddImagebtn.setPreferredSize(new java.awt.Dimension(80, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jInformationConference.add(jAddImagebtn, gridBagConstraints);

        jPlace.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPlace.setText("Place");
        jPlace.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jInformationConference.add(jPlace, gridBagConstraints);

        jPlaceChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPlaceChooser.setBorder(null);
        jPlaceChooser.setPreferredSize(new java.awt.Dimension(400, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jInformationConference.add(jPlaceChooser, gridBagConstraints);

        jAddNewPlace.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jAddNewPlace.setText("ADD");
        jAddNewPlace.setPreferredSize(new java.awt.Dimension(80, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jInformationConference.add(jAddNewPlace, gridBagConstraints);

        jDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDate.setText("Date");
        jDate.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        jInformationConference.add(jDate, gridBagConstraints);

        jDateChooser.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jDateChooser.setPreferredSize(new java.awt.Dimension(400, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        jInformationConference.add(jDateChooser, gridBagConstraints);

        jStart.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jStart.setText("Start");
        jStart.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        jInformationConference.add(jStart, gridBagConstraints);

        JSpinner.DateEditor deStart = new JSpinner.DateEditor(jStartTime, "HH:mm:ss");

        jStartTime.setEditor(deStart);
        jStartTime.setPreferredSize(new java.awt.Dimension(100, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jInformationConference.add(jStartTime, gridBagConstraints);

        jEnd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jEnd.setText("End");
        jEnd.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 0);
        jInformationConference.add(jEnd, gridBagConstraints);

        jEndTime.setPreferredSize(new java.awt.Dimension(100, 40));
        JSpinner.DateEditor deEnd = new JSpinner.DateEditor(jEndTime, "HH:mm:ss");

        jEndTime.setEditor(deEnd);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jInformationConference.add(jEndTime, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Brief Description");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jInformationConference.add(jLabel1, gridBagConstraints);

        jDetail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDetail.setText("Detail Decription");
        jDetail.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jInformationConference.add(jDetail, gridBagConstraints);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 150));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jInformationConference.add(jScrollPane1, gridBagConstraints);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(400, 100));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jScrollPane2.setViewportView(jTextArea2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jInformationConference.add(jScrollPane2, gridBagConstraints);

        jLabel2.setPreferredSize(new java.awt.Dimension(400, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        jInformationConference.add(jLabel2, gridBagConstraints);

        getContentPane().add(jInformationConference, java.awt.BorderLayout.NORTH);

        jFooter.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 5));
        jFooter.setPreferredSize(new java.awt.Dimension(600, 50));
        jFooter.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("OK");
        jFooter.add(jButton1, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jFooter, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewConference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewConference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewConference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewConference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewConference().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddImagebtn;
    private javax.swing.JButton jAddNewPlace;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jDate;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jDetail;
    private javax.swing.JLabel jEnd;
    private javax.swing.JSpinner jEndTime;
    private javax.swing.JPanel jFooter;
    private javax.swing.JLabel jImage;
    private javax.swing.JTextField jImageText;
    private javax.swing.JPanel jInformationConference;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jName;
    private javax.swing.JTextField jNameText;
    private javax.swing.JLabel jPlace;
    private javax.swing.JComboBox<String> jPlaceChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jStart;
    private javax.swing.JSpinner jStartTime;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
