/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.color.ColorSpace;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicComboBoxUI;

/**
 *
 * @author ADMIN
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    final static private Color deufault = new Color(58, 1, 108);
    final static private Color colorCliked = new Color(84, 3, 156);
    final static private Color colorMoved = new Color(67, 4, 123);

    public MainScreen() {
        initComponents();
//        jComboBox1.setUI(new BasicComboBoxUI() {
//            protected JButton createArrowButton() {
//                return new JButton() {
//                public int getWidth() {
//                return 0;
//            }
//        };
//    }
//});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jCardLayout = new javax.swing.JPanel();
        jCard1 = new javax.swing.JPanel();
        jCard2 = new javax.swing.JPanel();
        jCard3 = new javax.swing.JPanel();
        jCard4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jMenu = new javax.swing.JPanel();
        jButtonMenu = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jHomePnl = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jStatisticPnl = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jConferencesPnl = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jUsersPnl = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jExitPnl = new javax.swing.JPanel();
        jButtonExitPnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 0, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jCardLayout.setLayout(new java.awt.BorderLayout());

        jCard1.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jCard1Layout = new javax.swing.GroupLayout(jCard1);
        jCard1.setLayout(jCard1Layout);
        jCard1Layout.setHorizontalGroup(
            jCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jCard1Layout.setVerticalGroup(
            jCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jCardLayout.add(jCard1, java.awt.BorderLayout.CENTER);

        jCard2.setBackground(new java.awt.Color(102, 255, 0));
        jCard2.setLayout(new java.awt.BorderLayout());
        jCardLayout.add(jCard2, java.awt.BorderLayout.PAGE_START);

        jCard3.setBackground(new java.awt.Color(102, 102, 0));

        javax.swing.GroupLayout jCard3Layout = new javax.swing.GroupLayout(jCard3);
        jCard3.setLayout(jCard3Layout);
        jCard3Layout.setHorizontalGroup(
            jCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1203, Short.MAX_VALUE)
        );
        jCard3Layout.setVerticalGroup(
            jCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jCardLayout.add(jCard3, java.awt.BorderLayout.PAGE_END);

        jCard4.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jCard4Layout = new javax.swing.GroupLayout(jCard4);
        jCard4.setLayout(jCard4Layout);
        jCard4Layout.setHorizontalGroup(
            jCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1203, Short.MAX_VALUE)
        );
        jCard4Layout.setVerticalGroup(
            jCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jCardLayout.add(jCard4, java.awt.BorderLayout.LINE_END);

        jPanel3.add(jCardLayout, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 590));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(58, 1, 108));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 350));
        jPanel5.setLayout(new java.awt.GridLayout(0, 1));

        jMenu.setBackground(new java.awt.Color(58, 1, 108));
        jMenu.setLayout(new java.awt.BorderLayout());

        jButtonMenu.setBackground(new java.awt.Color(58, 1, 108));
        jButtonMenu.setPreferredSize(new java.awt.Dimension(50, 0));
        jButtonMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonMenuMouseMoved(evt);
            }
        });
        jButtonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMenuMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonMenuMouseReleased(evt);
            }
        });
        jButtonMenu.setLayout(new java.awt.BorderLayout());

        jLabel13.setBackground(new java.awt.Color(58, 1, 108));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/menu.png"))); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(50, 0));
        jButtonMenu.add(jLabel13, java.awt.BorderLayout.WEST);

        jMenu.add(jButtonMenu, java.awt.BorderLayout.WEST);

        jPanel5.add(jMenu);

        jHomePnl.setBackground(new java.awt.Color(58, 1, 108));
        jHomePnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jHomePnlMouseMoved(evt);
            }
        });
        jHomePnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jHomePnlMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jHomePnlMousePressed(evt);
            }
        });
        jHomePnl.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/home-run.png"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 24));
        jHomePnl.add(jLabel4, java.awt.BorderLayout.WEST);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Home");
        jHomePnl.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel5.add(jHomePnl);

        jStatisticPnl.setBackground(new java.awt.Color(58, 1, 108));
        jStatisticPnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jStatisticPnlMouseMoved(evt);
            }
        });
        jStatisticPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jStatisticPnlMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jStatisticPnlMouseReleased(evt);
            }
        });
        jStatisticPnl.setLayout(new java.awt.BorderLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/home-run.png"))); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 24));
        jStatisticPnl.add(jLabel7, java.awt.BorderLayout.WEST);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Statistics");
        jStatisticPnl.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel5.add(jStatisticPnl);

        jConferencesPnl.setBackground(new java.awt.Color(58, 1, 108));
        jConferencesPnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jConferencesPnlMouseMoved(evt);
            }
        });
        jConferencesPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jConferencesPnlMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jConferencesPnlMouseReleased(evt);
            }
        });
        jConferencesPnl.setLayout(new java.awt.BorderLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/home-run.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(50, 24));
        jConferencesPnl.add(jLabel9, java.awt.BorderLayout.WEST);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Conferences");
        jConferencesPnl.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel5.add(jConferencesPnl);

        jUsersPnl.setBackground(new java.awt.Color(58, 1, 108));
        jUsersPnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jUsersPnlMouseMoved(evt);
            }
        });
        jUsersPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jUsersPnlMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jUsersPnlMouseReleased(evt);
            }
        });
        jUsersPnl.setLayout(new java.awt.BorderLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/home-run.png"))); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(50, 24));
        jUsersPnl.add(jLabel11, java.awt.BorderLayout.WEST);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Users");
        jUsersPnl.add(jLabel12, java.awt.BorderLayout.CENTER);

        jPanel5.add(jUsersPnl);

        jPanel2.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel6.setBackground(new java.awt.Color(58, 1, 108));
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 290));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel2, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(new java.awt.Color(58, 1, 108));
        jPanel7.setPreferredSize(new java.awt.Dimension(1200, 80));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(58, 1, 108));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 100));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Brush Script Std", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONFERENCE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jExitPnl.setBackground(new java.awt.Color(58, 1, 108));
        jExitPnl.setPreferredSize(new java.awt.Dimension(40, 30));
        jExitPnl.setLayout(new java.awt.BorderLayout());

        jButtonExitPnl.setBackground(new java.awt.Color(58, 1, 108));
        jButtonExitPnl.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonExitPnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonExitPnlMouseMoved(evt);
            }
        });
        jButtonExitPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonExitPnlMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonExitPnlMouseReleased(evt);
            }
        });
        jButtonExitPnl.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setPreferredSize(new java.awt.Dimension(30, 29));
        jButtonExitPnl.add(jLabel2, java.awt.BorderLayout.EAST);

        jExitPnl.add(jButtonExitPnl, java.awt.BorderLayout.EAST);

        jPanel10.add(jExitPnl, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(new java.awt.Color(58, 1, 108));
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 50));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jPanel9.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/login.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });
        jPanel9.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel9);

        jPanel10.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel10, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel7, java.awt.BorderLayout.NORTH);

        jPanel8.setBackground(new java.awt.Color(58, 1, 108));
        jPanel8.setPreferredSize(new java.awt.Dimension(1200, 30));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("@Author: Lê Tấn Hưng @MSSV: 1712479   ");
        jLabel3.setPreferredSize(new java.awt.Dimension(300, 13));
        jPanel8.add(jLabel3, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel8, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jHomePnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomePnlMousePressed
        // TODO add your handling code here:
        setColorClicked(jHomePnl);
        resetColorUnClicked(jStatisticPnl);
        resetColorUnClicked(jConferencesPnl);
        resetColorUnClicked(jUsersPnl);
        jCardLayout.removeAll();
        jCardLayout.add(jCard1);
        jCardLayout.repaint();
        jCardLayout.revalidate();
    }//GEN-LAST:event_jHomePnlMousePressed

    private void jStatisticPnlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStatisticPnlMouseReleased
        // TODO add your handling code here:
        setColorClicked(jStatisticPnl);
        resetColorUnClicked(jHomePnl);
        resetColorUnClicked(jConferencesPnl);
        resetColorUnClicked(jUsersPnl);
        setColorClicked(jStatisticPnl);
        jCardLayout.removeAll();
        jCardLayout.add(jCard2);
        jCardLayout.repaint();
        jCardLayout.revalidate();

    }//GEN-LAST:event_jStatisticPnlMouseReleased

    private void jConferencesPnlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jConferencesPnlMouseReleased
        // TODO add your handling code here
        setColorClicked(jConferencesPnl);
        resetColorUnClicked(jHomePnl);
        resetColorUnClicked(jStatisticPnl);
        resetColorUnClicked(jUsersPnl);
        jCardLayout.removeAll();
        jCardLayout.add(jCard3);
        jCardLayout.repaint();
        jCardLayout.revalidate();
    }//GEN-LAST:event_jConferencesPnlMouseReleased

    private void jUsersPnlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUsersPnlMouseReleased
        // TODO add your handling code here:
        setColorClicked(jUsersPnl);
        resetColorUnClicked(jHomePnl);
        resetColorUnClicked(jStatisticPnl);
        resetColorUnClicked(jConferencesPnl);
        jCardLayout.removeAll();
        jCardLayout.add(jCard4);
        jCardLayout.repaint();
        jCardLayout.revalidate();
    }//GEN-LAST:event_jUsersPnlMouseReleased

    private void jHomePnlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomePnlMouseMoved
        // TODO add your handling code here:
        if (jHomePnl.getBackground() != colorCliked)
            setColorMoved(jHomePnl);
    }//GEN-LAST:event_jHomePnlMouseMoved

    private void jHomePnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomePnlMouseExited
        // TODO add your handling code here:
        if (jHomePnl.getBackground() != colorCliked)
            resetColorUnClicked(jHomePnl);
    }//GEN-LAST:event_jHomePnlMouseExited

    private void jStatisticPnlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStatisticPnlMouseMoved
        // TODO add your handling code here:
        if (jStatisticPnl.getBackground() != colorCliked)
            setColorMoved(jStatisticPnl);
    }//GEN-LAST:event_jStatisticPnlMouseMoved

    private void jStatisticPnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStatisticPnlMouseExited
        // TODO add your handling code here:
        if (jStatisticPnl.getBackground() != colorCliked)
            resetColorUnClicked(jStatisticPnl);
    }//GEN-LAST:event_jStatisticPnlMouseExited

    private void jConferencesPnlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jConferencesPnlMouseMoved
        // TODO add your handling code here:
        if (jConferencesPnl.getBackground() != colorCliked)
            setColorMoved(jConferencesPnl);
    }//GEN-LAST:event_jConferencesPnlMouseMoved

    private void jConferencesPnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jConferencesPnlMouseExited
        // TODO add your handling code here:
        if (jConferencesPnl.getBackground() != colorCliked)
            resetColorUnClicked(jConferencesPnl);
    }//GEN-LAST:event_jConferencesPnlMouseExited

    private void jUsersPnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUsersPnlMouseExited
        // TODO add your handling code here:
        if (jUsersPnl.getBackground() != colorCliked)
            resetColorUnClicked(jUsersPnl);
    }//GEN-LAST:event_jUsersPnlMouseExited

    private void jUsersPnlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUsersPnlMouseMoved
        // TODO add your handling code here:    
        if (jUsersPnl.getBackground() != colorCliked)
            setColorMoved(jUsersPnl);
    }//GEN-LAST:event_jUsersPnlMouseMoved

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
        // TODO add your handling code here:

       

        
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jButtonExitPnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExitPnlMouseExited
        // TODO add your handling code here:
        resetColorUnClicked(jButtonExitPnl);
    }//GEN-LAST:event_jButtonExitPnlMouseExited

    private void jButtonExitPnlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExitPnlMouseMoved
        // TODO add your handling code here:
        setColorClicked(jButtonExitPnl);
    }//GEN-LAST:event_jButtonExitPnlMouseMoved

    private void jButtonExitPnlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExitPnlMouseReleased
        // TODO add your handling code here:
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/Picture/Delete.png"));

        int respone = JOptionPane.showConfirmDialog(this, "Do you want to continue action?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, imageIcon);

        if (respone == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_jButtonExitPnlMouseReleased

    private void jButtonMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenuMouseExited
        // TODO add your handling code here:
        resetColorUnClicked(jButtonMenu);
    }//GEN-LAST:event_jButtonMenuMouseExited

    private void jButtonMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenuMouseMoved
        // TODO add your handling code here:
        setColorMoved(jButtonMenu);
    }//GEN-LAST:event_jButtonMenuMouseMoved

    private void jButtonMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenuMouseReleased
        // TODO add your handling code here:
          // TODO add your handling code here:
         if (jPanel2.getWidth() == 200) {
            Thread thread = new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 200; i >= 50; i--) {
                            Thread.sleep(1);
                            jPanel2.setSize(i, 640);
                            jPanel2.setPreferredSize(new Dimension(i, 0));
                            repaint();
                            revalidate();

                        }
                        System.out.println(jPanel2.getWidth());
                    } catch (Exception e) {
                    }
                }
            });
            thread.start();

        }

        if (jPanel2.getWidth() == 50) {
            Thread thread = new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 50; i <= 200; i++) {
                            Thread.sleep(1);
                            jPanel2.setSize(i, 640);
                            jPanel2.setPreferredSize(new Dimension(i, 0));
                            repaint();
                            revalidate();
                        }
                    } catch (Exception e) {
                    }
                }
            });
            thread.start();
        }
    }//GEN-LAST:event_jButtonMenuMouseReleased

    void setColorClicked(JPanel jp) {
        jp.setBackground(colorCliked);

    }

    void setColorMoved(JPanel jp) {
        jp.setBackground(colorMoved);
    }

    void resetColorUnClicked(JPanel jp) {
        jp.setBackground(deufault);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jButtonExitPnl;
    private javax.swing.JPanel jButtonMenu;
    private javax.swing.JPanel jCard1;
    private javax.swing.JPanel jCard2;
    private javax.swing.JPanel jCard3;
    private javax.swing.JPanel jCard4;
    private javax.swing.JPanel jCardLayout;
    private javax.swing.JPanel jConferencesPnl;
    private javax.swing.JPanel jExitPnl;
    private javax.swing.JPanel jHomePnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jStatisticPnl;
    private javax.swing.JPanel jUsersPnl;
    // End of variables declaration//GEN-END:variables
}
