/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author ADMIN
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 204));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setOpaque(false);

        jTextArea1.setBackground(new java.awt.Color(255, 153, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("ádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfasádfsadfsadfasdfsadfsdafsadfas");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );

        add(jLayeredPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
