/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialog;

import Business.AccountBus;
import MainScreenUI.MainScreen;
import POJO.Account;
import POJO.User;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class LoginDialog extends java.awt.Dialog {

    /**
     * Creates new form LoginDialog
     */
    public LoginDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        informationLoginPanel = new javax.swing.JPanel();
        jUserName = new javax.swing.JLabel();
        jUsernameTF = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPassword = new javax.swing.JLabel();
        jPasswordTF = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jKeepLogin = new javax.swing.JCheckBox();
        jLoginbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jShowPasswordbtn = new javax.swing.JButton();
        jExitbtn = new javax.swing.JButton();

        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        loginPanel.setBackground(new java.awt.Color(0, 153, 153));
        loginPanel.setPreferredSize(new java.awt.Dimension(500, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/congress.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CONFERENCE");

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 2, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Come Fly With Us");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(loginPanel, java.awt.BorderLayout.CENTER);

        informationLoginPanel.setBackground(new java.awt.Color(5, 38, 17));
        informationLoginPanel.setPreferredSize(new java.awt.Dimension(300, 0));

        jUserName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jUserName.setForeground(new java.awt.Color(255, 255, 255));
        jUserName.setText("User name");
        jUserName.setPreferredSize(new java.awt.Dimension(94, 30));

        jUsernameTF.setBackground(new java.awt.Color(5, 38, 17));
        jUsernameTF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jUsernameTF.setForeground(new java.awt.Color(204, 204, 204));
        jUsernameTF.setText("Enter your username");
        jUsernameTF.setBorder(null);
        jUsernameTF.setOpaque(false);
        jUsernameTF.setPreferredSize(new java.awt.Dimension(135, 30));
        jUsernameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jUsernameTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jUsernameTFFocusLost(evt);
            }
        });

        jPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPassword.setText("Password");
        jPassword.setPreferredSize(new java.awt.Dimension(88, 30));

        jPasswordTF.setBackground(new java.awt.Color(5, 38, 17));
        jPasswordTF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPasswordTF.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordTF.setText("123456789");
        jPasswordTF.setBorder(null);
        jPasswordTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordTFFocusLost(evt);
            }
        });

        jKeepLogin.setBackground(new java.awt.Color(5, 38, 17));
        jKeepLogin.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jKeepLogin.setForeground(new java.awt.Color(204, 204, 204));
        jKeepLogin.setText("Keep me logged in");

        jLoginbtn.setBackground(new java.awt.Color(102, 102, 255));
        jLoginbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLoginbtn.setForeground(new java.awt.Color(255, 255, 255));
        jLoginbtn.setText("Login");
        jLoginbtn.setBorderPainted(false);
        jLoginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLoginbtnMouseReleased(evt);
            }
        });
        jLoginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginbtnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/login.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setRequestFocusEnabled(false);

        jLabel4.setText("jLabel4");

        jLabel6.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Forgot Password?");

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Create an account");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setBorderPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        jShowPasswordbtn.setBackground(new java.awt.Color(5, 38, 17));
        jShowPasswordbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/icons8_invisible_20px.png"))); // NOI18N
        jShowPasswordbtn.setBorder(null);
        jShowPasswordbtn.setBorderPainted(false);
        jShowPasswordbtn.setContentAreaFilled(false);
        jShowPasswordbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jShowPasswordbtnMouseReleased(evt);
            }
        });

        jExitbtn.setBackground(new java.awt.Color(51, 102, 255));
        jExitbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jExitbtn.setForeground(new java.awt.Color(255, 255, 255));
        jExitbtn.setText("X");
        jExitbtn.setToolTipText("");
        jExitbtn.setBorder(null);
        jExitbtn.setBorderPainted(false);
        jExitbtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jExitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jExitbtnMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout informationLoginPanelLayout = new javax.swing.GroupLayout(informationLoginPanel);
        informationLoginPanel.setLayout(informationLoginPanelLayout);
        informationLoginPanelLayout.setHorizontalGroup(
            informationLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationLoginPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(informationLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationLoginPanelLayout.createSequentialGroup()
                        .addComponent(jPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jShowPasswordbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(informationLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2)
                        .addComponent(jUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jUsernameTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jKeepLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                        .addComponent(jLoginbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(informationLoginPanelLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationLoginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jExitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        informationLoginPanelLayout.setVerticalGroup(
            informationLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationLoginPanelLayout.createSequentialGroup()
                .addComponent(jExitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(informationLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationLoginPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4))
                    .addGroup(informationLoginPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordTF, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jShowPasswordbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jKeepLogin)
                .addGap(18, 18, 18)
                .addComponent(jLoginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(informationLoginPanel, java.awt.BorderLayout.EAST);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jUsernameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameTFFocusGained
        // TODO add your handling code here:
        if (jUsernameTF.getText().compareTo("") == 0 || jUsernameTF.getText().compareTo("Enter your username") == 0)
        jUsernameTF.setText("");
    }//GEN-LAST:event_jUsernameTFFocusGained

    private void jUsernameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameTFFocusLost
        // TODO add your handling code here:
        if (jUsernameTF.getText().compareTo("") == 0)
        jUsernameTF.setText("Enter your username");
    }//GEN-LAST:event_jUsernameTFFocusLost

    private void jPasswordTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordTFFocusGained
        // TODO add your handling code here:
        if (jPasswordTF.getText().compareTo("") == 0 || jPasswordTF.getText().compareTo("123456789") == 0)
        jPasswordTF.setText("");
    }//GEN-LAST:event_jPasswordTFFocusGained

    private void jPasswordTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordTFFocusLost
        // TODO add your handling code here:
        if (jPasswordTF.getText().compareTo("") == 0)
        jPasswordTF.setText("123456789");
    }//GEN-LAST:event_jPasswordTFFocusLost

    private void jLoginbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginbtnMouseReleased
        // TODO add your handling code here:
        switch (AccountBus.checkAccount(jUsernameTF.getText(), jPasswordTF.getText())) {
            case -1:
            JOptionPane.showMessageDialog(this, "User name does not already exits");
            break;
            case 0:
            JOptionPane.showMessageDialog(this, "Password is wrong");
            break;
            case 1:
            JOptionPane.showMessageDialog(this, "Success");
            Account account = AccountBus.getAccountByUserName(jUsernameTF.getText());
            Object[] users = (account.getUsers().toArray());
            User user = (User) users[0];
            MainScreen.getInstance().setUser(user);
            setVisible(false);
            break;
        }

    }//GEN-LAST:event_jLoginbtnMouseReleased

    private void jLoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginbtnActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
        setVisible(false);
        new RegisterDialog(MainScreen.getInstance(), true).setVisible(true);
    }//GEN-LAST:event_jButton1MouseReleased

    private void jShowPasswordbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jShowPasswordbtnMouseReleased
        // TODO add your handling code here:
        if (jPasswordTF.getEchoChar() == '*') {
            jPasswordTF.setEchoChar((char) 0);
            jShowPasswordbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/icons8_eye_20px.png")));
        } else {
            jShowPasswordbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/icons8_invisible_20px.png")));
            jPasswordTF.setEchoChar('*');
        }
    }//GEN-LAST:event_jShowPasswordbtnMouseReleased

    private void jExitbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitbtnMouseReleased
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jExitbtnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginDialog dialog = new LoginDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel informationLoginPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jExitbtn;
    private javax.swing.JCheckBox jKeepLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jLoginbtn;
    private javax.swing.JLabel jPassword;
    private javax.swing.JPasswordField jPasswordTF;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton jShowPasswordbtn;
    private javax.swing.JLabel jUserName;
    private javax.swing.JTextField jUsernameTF;
    private javax.swing.JPanel loginPanel;
    // End of variables declaration//GEN-END:variables
}
