package POJO;
// Generated Jul 2, 2020, 12:08:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private String id;
     private String userName;
     private String password;
     private Set<User> users = new HashSet<User>(0);

    public Account() {
    }

	
    public Account(String id) {
        this.id = id;
    }
    public Account(String id, String userName, String password, Set<User> users) {
       this.id = id;
       this.userName = userName;
       this.password = password;
       this.users = users;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


