package POJO;
// Generated Jul 5, 2020, 9:32:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="account"
    ,catalog="conferencemanagement"
)
public class Account  implements java.io.Serializable {


     private String id;
     private String userName;
     private String password;
     private Set<User> users = new HashSet<User>(0);

    public Account() {
    }

	
    public Account(String id) {
        this.id = id;
    }
    public Account(String userName, String password) {
       this.userName = userName;
       this.password = password;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="UserName", length=32)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="Password", length=32)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="account")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


