package POJO;
// Generated Jul 2, 2020, 12:08:59 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conference generated by hbm2java
 */
public class Conference  implements java.io.Serializable {


     private String id;
     private String name;
     private String briefDescription;
     private String detailDescription;
     private String image;
     private Date startTime;
     private Date endTime;
     private Integer limitedQuantity;
     private Set<Place> places = new HashSet<Place>(0);
     private Set<UserConference> userConferences = new HashSet<UserConference>(0);

    public Conference() {
    }

	
    public Conference(String id) {
        this.id = id;
    }
    public Conference(String id, String name, String briefDescription, String detailDescription, String image, Date startTime, Date endTime, Integer limitedQuantity, Set<Place> places, Set<UserConference> userConferences) {
       this.id = id;
       this.name = name;
       this.briefDescription = briefDescription;
       this.detailDescription = detailDescription;
       this.image = image;
       this.startTime = startTime;
       this.endTime = endTime;
       this.limitedQuantity = limitedQuantity;
       this.places = places;
       this.userConferences = userConferences;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBriefDescription() {
        return this.briefDescription;
    }
    
    public void setBriefDescription(String briefDescription) {
        this.briefDescription = briefDescription;
    }
    public String getDetailDescription() {
        return this.detailDescription;
    }
    
    public void setDetailDescription(String detailDescription) {
        this.detailDescription = detailDescription;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public Integer getLimitedQuantity() {
        return this.limitedQuantity;
    }
    
    public void setLimitedQuantity(Integer limitedQuantity) {
        this.limitedQuantity = limitedQuantity;
    }
    public Set<Place> getPlaces() {
        return this.places;
    }
    
    public void setPlaces(Set<Place> places) {
        this.places = places;
    }
    public Set<UserConference> getUserConferences() {
        return this.userConferences;
    }
    
    public void setUserConferences(Set<UserConference> userConferences) {
        this.userConferences = userConferences;
    }




}


