package POJO;
// Generated Jul 5, 2020, 9:32:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Place generated by hbm2java
 */
@Entity
@Table(name="place"
    ,catalog="conferencemanagement"
)
public class Place  implements java.io.Serializable, Comparable<Place> {


     private String id;
     private String name;
     private String address;
     private Integer capacity;
     private Byte isDelete;
     private Set<Conference> conferences = new HashSet<Conference>(0);

    public Place() {
    }

	
    public Place(String id) {
        this.id = id;
    }
    public Place(String name, String address, Integer capacity) {
       this.name = name;
       this.address = address;
       this.capacity = capacity;
       this.isDelete = 0;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, length=4)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="Name", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Address", length=256)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="Capacity")
    public Integer getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    
    @Column(name="IsDelete")
    public Byte getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="place")
    public Set<Conference> getConferences() {
        return this.conferences;
    }
    
    public void setConferences(Set<Conference> conferences) {
        this.conferences = conferences;
    }

    @Override
    public int compareTo(Place o) {
        return getName().compareTo(o.getName());
    }




}


