package POJO;
// Generated Jul 9, 2020, 5:02:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserConferenceId generated by hbm2java
 */
@Embeddable
public class UserConferenceId  implements java.io.Serializable {


     private String idconference;
     private String iduser;

    public UserConferenceId() {
    }

    public UserConferenceId(String idconference, String iduser) {
       this.idconference = idconference;
       this.iduser = iduser;
    }
   


    @Column(name="IDConference", nullable=false, length=4)
    public String getIdconference() {
        return this.idconference;
    }
    
    public void setIdconference(String idconference) {
        this.idconference = idconference;
    }


    @Column(name="IDUser", nullable=false, length=10)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserConferenceId) ) return false;
		 UserConferenceId castOther = ( UserConferenceId ) other; 
         
		 return ( (this.getIdconference()==castOther.getIdconference()) || ( this.getIdconference()!=null && castOther.getIdconference()!=null && this.getIdconference().equals(castOther.getIdconference()) ) )
 && ( (this.getIduser()==castOther.getIduser()) || ( this.getIduser()!=null && castOther.getIduser()!=null && this.getIduser().equals(castOther.getIduser()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdconference() == null ? 0 : this.getIdconference().hashCode() );
         result = 37 * result + ( getIduser() == null ? 0 : this.getIduser().hashCode() );
         return result;
   }   


}


