package POJO;
// Generated Jul 2, 2020, 12:08:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String id;
     private Account account;
     private String name;
     private String email;
     private Boolean isAdmin;
     private Set<UserConference> userConferences = new HashSet<UserConference>(0);

    public User() {
    }

	
    public User(String id) {
        this.id = id;
    }
    public User(String id, Account account, String name, String email, Boolean isAdmin, Set<UserConference> userConferences) {
       this.id = id;
       this.account = account;
       this.name = name;
       this.email = email;
       this.isAdmin = isAdmin;
       this.userConferences = userConferences;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public Set<UserConference> getUserConferences() {
        return this.userConferences;
    }
    
    public void setUserConferences(Set<UserConference> userConferences) {
        this.userConferences = userConferences;
    }




}


