/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ContentUI;

import Business.UserConferenceBus;
import MainScreenUI.MainScreen;
import POJO.Conference;
import POJO.Place;
import POJO.UserConference;
import java.awt.Image;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class DetailConference extends javax.swing.JPanel {

    /**
     * Creates new form DetailConference
     */
    MainScreen mainScreen;
    Conference conference;
    int page;

    public DetailConference(Conference conference, MainScreen mainScreen, int page) {

        initComponents();
        this.mainScreen = mainScreen;
        this.conference = conference;
        this.page = page;
        resetData();
    }

    void resetData() {

        ImageIcon imageIcon = new ImageIcon(new File("").getAbsolutePath() + "\\Picture\\" + conference.getImage());
        Image image = imageIcon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        jImage.setIcon(new ImageIcon(image));
        jNameConference.setText(conference.getName());
        jBriefDescription.setText(conference.getBriefDescription());
        jDetailDescription.setText(conference.getDetailDescription());

        Place place = conference.getPlace();
        jPlaceNameTF.setText(place.getName());
        jAddressTF.setText(place.getAddress());
        jCapacityTF.setText(String.valueOf(UserConferenceBus.getTheNumberOfUserIsNotDeclined(conference)) + "/" + String.valueOf(conference.getParticipants()));

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        jDateTF.setText(dateFormat.format(conference.getStartTime()));
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
        jStartTF.setText(timeFormat.format(conference.getStartTime()));
        jEndTF.setText(timeFormat.format(conference.getEndTime()));

        List<UserConference> userConferenceList = UserConferenceBus.getListUserConferenceIsNotDeclinedByConference(conference);

        DefaultTableModel tm = (DefaultTableModel) jTable.getModel();
        for (int i = tm.getRowCount() - 1; i >= 0; i--) {
            tm.removeRow(i);
        }

        for (int i = 0; i < userConferenceList.size(); i++) {
            tm.addRow(new Object[]{i + 1, userConferenceList.get(i).getUser().getName(), userConferenceList.get(i).getUser().getAccount().getUserName(), userConferenceList.get(i).getUser().getEmail(), userConferenceList.get(i).getIsAccepted() == 1 ? "is Accepted" : "is Watting"});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jBackbtn = new javax.swing.JButton();
        jRegisterbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jImage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jNameConference = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jBriefDescription = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPlaceNamePnl = new javax.swing.JPanel();
        jPlaceName = new javax.swing.JLabel();
        jPlaceNameTF = new javax.swing.JTextField();
        jAdressPnl = new javax.swing.JPanel();
        jAddress = new javax.swing.JLabel();
        jAddressTF = new javax.swing.JTextField();
        jCapacityPnl = new javax.swing.JPanel();
        jCapacityTF = new javax.swing.JTextField();
        jCapacity = new javax.swing.JLabel();
        jTimePnl = new javax.swing.JPanel();
        jStartPnl = new javax.swing.JPanel();
        jStart = new javax.swing.JLabel();
        jStartTF = new javax.swing.JTextField();
        jEndPnl = new javax.swing.JPanel();
        jEnd = new javax.swing.JLabel();
        jEndTF = new javax.swing.JTextField();
        jDatePnl = new javax.swing.JPanel();
        jDate = new javax.swing.JLabel();
        jDateTF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDetailDescription = new javax.swing.JTextArea();
        jAttendList = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(224, 224, 250));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setPreferredSize(new java.awt.Dimension(1200, 590));
        setLayout(new java.awt.BorderLayout());

        jScrollPane3.setBackground(new java.awt.Color(224, 224, 250));
        jScrollPane3.setBorder(null);

        jPanel7.setBackground(new java.awt.Color(224, 224, 250));
        jPanel7.setPreferredSize(new java.awt.Dimension(1000, 800));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(600, 200));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.BorderLayout());

        jBackbtn.setText("Back");
        jBackbtn.setPreferredSize(new java.awt.Dimension(75, 21));
        jBackbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBackbtnMouseReleased(evt);
            }
        });
        jPanel6.add(jBackbtn, java.awt.BorderLayout.WEST);

        jRegisterbtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRegisterbtn.setText("Register");
        jRegisterbtn.setPreferredSize(new java.awt.Dimension(79, 40));
        jRegisterbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRegisterbtnMouseReleased(evt);
            }
        });
        jPanel6.add(jRegisterbtn, java.awt.BorderLayout.EAST);

        jPanel5.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(224, 224, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 150));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jImage.setText("Image");
        jImage.setOpaque(true);
        jImage.setPreferredSize(new java.awt.Dimension(200, 13));
        jPanel2.add(jImage, java.awt.BorderLayout.WEST);

        jPanel3.setBackground(new java.awt.Color(224, 224, 250));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jNameConference.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jNameConference.setForeground(new java.awt.Color(255, 0, 51));
        jNameConference.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNameConference.setText("Name Conference");
        jNameConference.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jNameConference.setPreferredSize(new java.awt.Dimension(50, 70));
        jPanel3.add(jNameConference, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 0, 5));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jBriefDescription.setEditable(false);
        jBriefDescription.setColumns(20);
        jBriefDescription.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBriefDescription.setLineWrap(true);
        jBriefDescription.setRows(5);
        jBriefDescription.setText("Brief Description");
        jBriefDescription.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jBriefDescription);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel5);

        jPanel1.setBackground(new java.awt.Color(224, 224, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 500));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(224, 224, 250));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 250));
        jPanel4.setLayout(new java.awt.GridLayout(0, 1));

        jPlaceNamePnl.setOpaque(false);
        jPlaceNamePnl.setLayout(new java.awt.BorderLayout());

        jPlaceName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPlaceName.setText("Place Name");
        jPlaceName.setPreferredSize(new java.awt.Dimension(100, 50));
        jPlaceNamePnl.add(jPlaceName, java.awt.BorderLayout.WEST);

        jPlaceNameTF.setEditable(false);
        jPlaceNameTF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPlaceNameTF.setText("jTextField1");
        jPlaceNameTF.setPreferredSize(new java.awt.Dimension(450, 40));
        jPlaceNamePnl.add(jPlaceNameTF, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPlaceNamePnl);

        jAdressPnl.setOpaque(false);
        jAdressPnl.setLayout(new java.awt.BorderLayout());

        jAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jAddress.setText("Adress");
        jAddress.setPreferredSize(new java.awt.Dimension(100, 50));
        jAdressPnl.add(jAddress, java.awt.BorderLayout.WEST);

        jAddressTF.setEditable(false);
        jAddressTF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jAddressTF.setText("jTextField2");
        jAddressTF.setPreferredSize(new java.awt.Dimension(450, 40));
        jAdressPnl.add(jAddressTF, java.awt.BorderLayout.CENTER);

        jPanel4.add(jAdressPnl);

        jCapacityPnl.setOpaque(false);
        jCapacityPnl.setLayout(new java.awt.BorderLayout());

        jCapacityTF.setEditable(false);
        jCapacityTF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCapacityTF.setText("jTextField3");
        jCapacityTF.setPreferredSize(new java.awt.Dimension(450, 40));
        jCapacityPnl.add(jCapacityTF, java.awt.BorderLayout.CENTER);

        jCapacity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCapacity.setText("Capacity");
        jCapacity.setPreferredSize(new java.awt.Dimension(100, 50));
        jCapacityPnl.add(jCapacity, java.awt.BorderLayout.WEST);

        jPanel4.add(jCapacityPnl);

        jTimePnl.setOpaque(false);
        jTimePnl.setLayout(new java.awt.BorderLayout());

        jStartPnl.setOpaque(false);
        jStartPnl.setPreferredSize(new java.awt.Dimension(500, 100));
        jStartPnl.setLayout(new java.awt.BorderLayout());

        jStart.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jStart.setText("Start");
        jStart.setPreferredSize(new java.awt.Dimension(100, 50));
        jStartPnl.add(jStart, java.awt.BorderLayout.WEST);

        jStartTF.setEditable(false);
        jStartTF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jStartTF.setText("jTextField5");
        jStartTF.setPreferredSize(new java.awt.Dimension(170, 40));
        jStartPnl.add(jStartTF, java.awt.BorderLayout.CENTER);

        jTimePnl.add(jStartPnl, java.awt.BorderLayout.WEST);

        jEndPnl.setOpaque(false);
        jEndPnl.setPreferredSize(new java.awt.Dimension(500, 100));
        jEndPnl.setLayout(new java.awt.BorderLayout());

        jEnd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jEnd.setText("End");
        jEnd.setPreferredSize(new java.awt.Dimension(100, 50));
        jEndPnl.add(jEnd, java.awt.BorderLayout.WEST);

        jEndTF.setEditable(false);
        jEndTF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jEndTF.setText("jTextField6");
        jEndTF.setPreferredSize(new java.awt.Dimension(170, 40));
        jEndPnl.add(jEndTF, java.awt.BorderLayout.CENTER);

        jTimePnl.add(jEndPnl, java.awt.BorderLayout.EAST);

        jPanel4.add(jTimePnl);

        jDatePnl.setOpaque(false);
        jDatePnl.setLayout(new java.awt.BorderLayout());

        jDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDate.setText("Date");
        jDate.setPreferredSize(new java.awt.Dimension(100, 50));
        jDatePnl.add(jDate, java.awt.BorderLayout.WEST);

        jDateTF.setEditable(false);
        jDateTF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDateTF.setText("jTextField4");
        jDateTF.setPreferredSize(new java.awt.Dimension(450, 40));
        jDatePnl.add(jDateTF, java.awt.BorderLayout.CENTER);

        jPanel4.add(jDatePnl);

        jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 0));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jDetailDescription.setEditable(false);
        jDetailDescription.setColumns(20);
        jDetailDescription.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDetailDescription.setLineWrap(true);
        jDetailDescription.setRows(5);
        jDetailDescription.setText("Detail Description");
        jDetailDescription.setWrapStyleWord(true);
        jDetailDescription.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jScrollPane2.setViewportView(jDetailDescription);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel1);

        jAttendList.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jAttendList.setText("Attendee List ");
        jAttendList.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        jPanel7.add(jAttendList);

        jScrollPane4.setBackground(new java.awt.Color(224, 224, 250));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(452, 200));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Name", "User Name", "Email", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setGridColor(new java.awt.Color(224, 224, 250));
        jTable.setOpaque(false);
        jScrollPane4.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable.getColumnModel().getColumn(2).setPreferredWidth(300);
            jTable.getColumnModel().getColumn(3).setPreferredWidth(300);
        }

        jPanel7.add(jScrollPane4);

        jScrollPane3.setViewportView(jPanel7);

        add(jScrollPane3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jRegisterbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegisterbtnMouseReleased
        //TODO add your handling code here:
        if (mainScreen.getUser() == null) {
            String[] options = {"Log in", "Register"};
            int result = JOptionPane.showOptionDialog(
                    this,
                    "You need to log in",
                    "OPtion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null, //no custom icon
                    options, //button titles
                    options[0] //default button
            );

            if (result == JOptionPane.YES_OPTION) {
                mainScreen.login();
            } else if (result == JOptionPane.NO_OPTION) {
                mainScreen.register();
            }
        } else {
            UserConference userConference = new UserConference(conference, mainScreen.getUser());

            if (conference.getStartTime().compareTo(new Date()) <= 0) {
                JOptionPane.showMessageDialog(this, "This conference has already been organized");
                return;
            }

            if (UserConferenceBus.getUserConferenceInformation(userConference.getId()) != null) {
                JOptionPane.showMessageDialog(this, "You have already subscribed to this conference");
            } else {
                int result = JOptionPane.showConfirmDialog(mainScreen, "Do you want to register this conference?");

                if (result == JOptionPane.YES_OPTION) {
                    if (UserConferenceBus.getTheNumberOfUserIsNotDeclined(conference) >= conference.getParticipants()) {
                        JOptionPane.showMessageDialog(mainScreen, "Number of subscribers exceeded limit");
                    } else {
                        UserConferenceBus.insertNewUserConference(new UserConference(conference, mainScreen.getUser()));
                        JOptionPane.showMessageDialog(mainScreen, "Success");
                        resetData();

                    }

                }

            }

        }
    }//GEN-LAST:event_jRegisterbtnMouseReleased

    private void jBackbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackbtnMouseReleased
        // TODO add your handling code here:
        switch (page) {
            case 1:
                mainScreen.backToListConference();
                break;
            case 2:
                mainScreen.backToStatistic();
                break;
            case 3:
                mainScreen.backToConferenceUI();
                break;
            case 4:
                mainScreen.backToUserUI();
        }

    }//GEN-LAST:event_jBackbtnMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAddress;
    private javax.swing.JTextField jAddressTF;
    private javax.swing.JPanel jAdressPnl;
    private javax.swing.JLabel jAttendList;
    private javax.swing.JButton jBackbtn;
    private javax.swing.JTextArea jBriefDescription;
    private javax.swing.JLabel jCapacity;
    private javax.swing.JPanel jCapacityPnl;
    private javax.swing.JTextField jCapacityTF;
    private javax.swing.JLabel jDate;
    private javax.swing.JPanel jDatePnl;
    private javax.swing.JTextField jDateTF;
    private javax.swing.JTextArea jDetailDescription;
    private javax.swing.JLabel jEnd;
    private javax.swing.JPanel jEndPnl;
    private javax.swing.JTextField jEndTF;
    private javax.swing.JLabel jImage;
    private javax.swing.JLabel jNameConference;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jPlaceName;
    private javax.swing.JPanel jPlaceNamePnl;
    private javax.swing.JTextField jPlaceNameTF;
    private javax.swing.JButton jRegisterbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jStart;
    private javax.swing.JPanel jStartPnl;
    private javax.swing.JTextField jStartTF;
    private javax.swing.JTable jTable;
    private javax.swing.JPanel jTimePnl;
    // End of variables declaration//GEN-END:variables
}
