/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ContentUI;

/**
 *
 * @author ADMIN
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JPanel();
        jNameApp = new javax.swing.JLabel();
        jIntroduce = new javax.swing.JLabel();
        jUniversity = new javax.swing.JLabel();
        jImageConference = new javax.swing.JPanel();
        jImage = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jHeader.setBackground(new java.awt.Color(255, 255, 255));
        jHeader.setPreferredSize(new java.awt.Dimension(1203, 150));
        jHeader.setLayout(new java.awt.BorderLayout());

        jNameApp.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jNameApp.setForeground(new java.awt.Color(102, 0, 153));
        jNameApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNameApp.setText("CONFERENCE APPLICATION");
        jNameApp.setPreferredSize(new java.awt.Dimension(516, 50));
        jHeader.add(jNameApp, java.awt.BorderLayout.NORTH);

        jIntroduce.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jIntroduce.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jIntroduce.setText("Frovide Conferences For Those Who Need It");
        jHeader.add(jIntroduce, java.awt.BorderLayout.CENTER);

        jUniversity.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jUniversity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUniversity.setText("University Of Science");
        jUniversity.setPreferredSize(new java.awt.Dimension(38, 50));
        jHeader.add(jUniversity, java.awt.BorderLayout.SOUTH);

        add(jHeader, java.awt.BorderLayout.PAGE_START);

        jImageConference.setBackground(new java.awt.Color(255, 255, 255));
        jImageConference.setLayout(new java.awt.BorderLayout());

        jImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/velocityca2019_og_image.jpg"))); // NOI18N
        jImage.setPreferredSize(new java.awt.Dimension(500, 13));
        jImageConference.add(jImage, java.awt.BorderLayout.CENTER);

        add(jImageConference, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jHeader;
    private javax.swing.JLabel jImage;
    private javax.swing.JPanel jImageConference;
    private javax.swing.JLabel jIntroduce;
    private javax.swing.JLabel jNameApp;
    private javax.swing.JLabel jUniversity;
    // End of variables declaration//GEN-END:variables
}
