/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ContentUI;

import Class.Conference;
import ComponentUI.ConferenceRenderCard;
import ComponentUI.ConferenceRenderList;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author ADMIN
 */
public class ListConference extends javax.swing.JPanel {

    /**
     * Creates new form ListConference
     */
    
    final static private Color deufault = new Color(58, 1, 108);
    final static private Color colorCliked = new Color(84, 3, 156);
    final static private Color colorMoved = new Color(74,2,137);
    final static private Color colorMoved_2 = new Color(220,220,255);
    
    public ListConference() {
        initComponents();
        createViewList();
        createViewCard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jListViewbtn = new javax.swing.JLabel();
        jCardViewbtn = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jResetbtn = new javax.swing.JLabel();
        jSearchPnl = new javax.swing.JPanel();
        jSearchbtn = new javax.swing.JLabel();
        jSearchText = new javax.swing.JTextField();
        jConferenceView = new javax.swing.JPanel();
        jListView = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListConferenceView = new javax.swing.JPanel();
        jCardView = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jCardConferenceView = new javax.swing.JPanel();
        jPaginationConference = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jFirstbtn = new javax.swing.JLabel();
        jPrebtn = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jNextbtn = new javax.swing.JLabel();
        jLastbtn = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(58, 1, 108));
        jPanel13.setPreferredSize(new java.awt.Dimension(0, 50));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(58, 1, 108));
        jPanel12.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jListViewbtn.setBackground(new java.awt.Color(84, 3, 156));
        jListViewbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jListViewbtn.setForeground(new java.awt.Color(255, 255, 255));
        jListViewbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/List_White.png"))); // NOI18N
        jListViewbtn.setText("List view");
        jListViewbtn.setOpaque(true);
        jListViewbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jListViewbtnMouseMoved(evt);
            }
        });
        jListViewbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jListViewbtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jListViewbtnMouseReleased(evt);
            }
        });
        jPanel12.add(jListViewbtn);

        jCardViewbtn.setBackground(new java.awt.Color(255, 255, 255));
        jCardViewbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCardViewbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Grid-View-black.png"))); // NOI18N
        jCardViewbtn.setText("Grid view");
        jCardViewbtn.setOpaque(true);
        jCardViewbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jCardViewbtnMouseMoved(evt);
            }
        });
        jCardViewbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCardViewbtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCardViewbtnMouseReleased(evt);
            }
        });
        jPanel12.add(jCardViewbtn);

        jPanel13.add(jPanel12, java.awt.BorderLayout.WEST);

        jPanel14.setBackground(new java.awt.Color(58, 1, 108));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel15.setBackground(new java.awt.Color(58, 1, 108));
        jPanel15.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jDateChooser1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jDateChooser1.setOpaque(false);
        jDateChooser1.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel15.add(jDateChooser1, java.awt.BorderLayout.CENTER);

        jPanel17.setOpaque(false);
        jPanel17.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel17, java.awt.BorderLayout.EAST);

        jPanel18.setOpaque(false);
        jPanel18.setPreferredSize(new java.awt.Dimension(200, 50));

        jResetbtn.setBackground(new java.awt.Color(58, 1, 108));
        jResetbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jResetbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Available-Updates-icon.png"))); // NOI18N
        jResetbtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jResetbtn.setOpaque(true);
        jResetbtn.setPreferredSize(new java.awt.Dimension(50, 50));
        jResetbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jResetbtnMouseMoved(evt);
            }
        });
        jResetbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jResetbtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jResetbtnMouseReleased(evt);
            }
        });
        jPanel18.add(jResetbtn);

        jPanel15.add(jPanel18, java.awt.BorderLayout.WEST);

        jPanel14.add(jPanel15, java.awt.BorderLayout.CENTER);

        jSearchPnl.setBackground(new java.awt.Color(58, 1, 108));
        jSearchPnl.setPreferredSize(new java.awt.Dimension(300, 50));
        jSearchPnl.setLayout(new java.awt.BorderLayout());

        jSearchbtn.setBackground(new java.awt.Color(58, 1, 108));
        jSearchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Search-icon.png"))); // NOI18N
        jSearchbtn.setOpaque(true);
        jSearchbtn.setPreferredSize(new java.awt.Dimension(50, 13));
        jSearchbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jSearchbtnMouseMoved(evt);
            }
        });
        jSearchbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jSearchbtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSearchbtnMouseReleased(evt);
            }
        });
        jSearchPnl.add(jSearchbtn, java.awt.BorderLayout.WEST);

        jSearchText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jSearchText.setText("Search name conference");
        jSearchText.setToolTipText("");
        jSearchText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSearchTextFocusLost(evt);
            }
        });
        jSearchPnl.add(jSearchText, java.awt.BorderLayout.CENTER);

        jPanel14.add(jSearchPnl, java.awt.BorderLayout.EAST);

        jPanel13.add(jPanel14, java.awt.BorderLayout.CENTER);

        add(jPanel13, java.awt.BorderLayout.NORTH);

        jConferenceView.setLayout(new java.awt.CardLayout());

        jListView.setBackground(new java.awt.Color(255, 255, 255));
        jListView.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jListView.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jListView.setInheritsPopupMenu(true);
        jListView.setLayout(new java.awt.BorderLayout(0, 10));

        jListConferenceView.setBackground(new java.awt.Color(255, 255, 255));
        jListConferenceView.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
        jScrollPane3.setViewportView(jListConferenceView);

        jListView.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jConferenceView.add(jListView, "card3");

        jCardView.setBackground(new java.awt.Color(255, 255, 255));
        jCardView.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jCardView.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jCardView.setInheritsPopupMenu(true);
        jCardView.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jCardConferenceView.setBackground(new java.awt.Color(255, 255, 255));
        jCardConferenceView.setLayout(new java.awt.GridLayout(0, 3, 10, 10));
        jScrollPane4.setViewportView(jCardConferenceView);

        jCardView.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jConferenceView.add(jCardView, "card2");

        add(jConferenceView, java.awt.BorderLayout.CENTER);

        jPaginationConference.setBackground(new java.awt.Color(58, 1, 108));
        jPaginationConference.setPreferredSize(new java.awt.Dimension(1198, 50));
        jPaginationConference.setLayout(new java.awt.BorderLayout());

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Page 1 for 1-6/100");
        jLabel20.setPreferredSize(new java.awt.Dimension(300, 13));
        jPaginationConference.add(jLabel20, java.awt.BorderLayout.WEST);

        jPanel16.setOpaque(false);
        jPanel16.setPreferredSize(new java.awt.Dimension(290, 50));
        jPanel16.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jFirstbtn.setBackground(new java.awt.Color(58, 1, 108));
        jFirstbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFirstbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Rewind-icon-2.png"))); // NOI18N
        jFirstbtn.setOpaque(true);
        jFirstbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jFirstbtnMouseMoved(evt);
            }
        });
        jFirstbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jFirstbtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jFirstbtnMouseReleased(evt);
            }
        });
        jPanel16.add(jFirstbtn);

        jPrebtn.setBackground(new java.awt.Color(58, 1, 108));
        jPrebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPrebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Chevron-Left-icon.png"))); // NOI18N
        jPrebtn.setOpaque(true);
        jPrebtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPrebtnMouseMoved(evt);
            }
        });
        jPrebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPrebtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPrebtnMouseReleased(evt);
            }
        });
        jPanel16.add(jPrebtn);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel16.add(jTextField1);

        jNextbtn.setBackground(new java.awt.Color(58, 1, 108));
        jNextbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNextbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Chevron-Right-icon.png"))); // NOI18N
        jNextbtn.setOpaque(true);
        jNextbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jNextbtnMouseMoved(evt);
            }
        });
        jNextbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jNextbtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jNextbtnMouseReleased(evt);
            }
        });
        jPanel16.add(jNextbtn);

        jLastbtn.setBackground(new java.awt.Color(58, 1, 108));
        jLastbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLastbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Fast-Forward-icon.png"))); // NOI18N
        jLastbtn.setOpaque(true);
        jLastbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLastbtnMouseMoved(evt);
            }
        });
        jLastbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLastbtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLastbtnMouseReleased(evt);
            }
        });
        jPanel16.add(jLastbtn);

        jPaginationConference.add(jPanel16, java.awt.BorderLayout.EAST);

        add(jPaginationConference, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jListViewbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListViewbtnMouseMoved
        // TODO add your handling code here:
        if(jListViewbtn.getBackground().equals(colorCliked) == false)
        jListViewbtn.setBackground(colorMoved_2);
    }//GEN-LAST:event_jListViewbtnMouseMoved

    private void jListViewbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListViewbtnMouseExited
        // TODO add your handling code here:
        if(jListViewbtn.getBackground().equals(colorCliked) == false)
        jListViewbtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_jListViewbtnMouseExited

    private void jListViewbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListViewbtnMouseReleased
        // TODO add your handling code here:
        jListViewbtn.setBackground(colorCliked);
        jListViewbtn.setForeground(Color.WHITE);
        jListViewbtn.setIcon(new ImageIcon(getClass().getResource("/Picture/List_White.png")));

        jCardViewbtn.setBackground(Color.WHITE);
        jCardViewbtn.setForeground(Color.BLACK);
        jCardViewbtn.setIcon(new ImageIcon(getClass().getResource("/Picture/Grid-View-black.png")));

        jConferenceView.removeAll();
        jConferenceView.add(jListView);
        jConferenceView.repaint();
        jConferenceView.revalidate();
    }//GEN-LAST:event_jListViewbtnMouseReleased

    private void jCardViewbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCardViewbtnMouseMoved
        // TODO add your handling code here:
        if(jCardViewbtn.getBackground().equals(colorCliked) == false)
        jCardViewbtn.setBackground(colorMoved_2);
    }//GEN-LAST:event_jCardViewbtnMouseMoved

    private void jCardViewbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCardViewbtnMouseExited
        // TODO add your handling code here:
        if(jCardViewbtn.getBackground().equals(colorCliked) == false)
        jCardViewbtn.setBackground(Color.WHITE);

    }//GEN-LAST:event_jCardViewbtnMouseExited

    private void jCardViewbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCardViewbtnMouseReleased
        // TODO add your handling code here:
        jCardViewbtn.setBackground(colorCliked);
        jCardViewbtn.setForeground(Color.WHITE);
        jCardViewbtn.setIcon(new ImageIcon(getClass().getResource("/Picture/Grid-View-white.png")));

        jListViewbtn.setBackground(Color.WHITE);
        jListViewbtn.setForeground(Color.BLACK);
        jListViewbtn.setIcon(new ImageIcon(getClass().getResource("/Picture/ListView.png")));

        jConferenceView.removeAll();
        jConferenceView.add(jCardView);
        jConferenceView.repaint();
        jConferenceView.revalidate();
    }//GEN-LAST:event_jCardViewbtnMouseReleased

    private void jResetbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jResetbtnMouseMoved
        // TODO add your handling code here:
        jResetbtn.setBackground(colorMoved);
    }//GEN-LAST:event_jResetbtnMouseMoved

    private void jResetbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jResetbtnMouseExited
        // TODO add your handling code here:
        jResetbtn.setBackground(deufault);
    }//GEN-LAST:event_jResetbtnMouseExited

    private void jResetbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jResetbtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jResetbtnMouseReleased

    private void jSearchbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchbtnMouseMoved
        // TODO add your handling code here:
        jSearchbtn.setBackground(colorMoved);
    }//GEN-LAST:event_jSearchbtnMouseMoved

    private void jSearchbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchbtnMouseExited
        // TODO add your handling code here:
        jSearchbtn.setBackground(deufault);
    }//GEN-LAST:event_jSearchbtnMouseExited

    private void jSearchbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchbtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchbtnMouseReleased

    private void jSearchTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSearchTextFocusLost
        // TODO add your handling code here:
        if(jSearchText.getText().compareTo("") == 0)
        jSearchText.setText("Search name conference");
    }//GEN-LAST:event_jSearchTextFocusLost

    private void jFirstbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFirstbtnMouseMoved
        // TODO add your handling code here:
        jFirstbtn.setBackground(colorMoved);
    }//GEN-LAST:event_jFirstbtnMouseMoved

    private void jFirstbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFirstbtnMouseExited
        // TODO add your handling code here:
        jFirstbtn.setBackground(deufault);
    }//GEN-LAST:event_jFirstbtnMouseExited

    private void jFirstbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFirstbtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jFirstbtnMouseReleased

    private void jPrebtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPrebtnMouseMoved
        // TODO add your handling code here:
        jPrebtn.setBackground(colorMoved);
    }//GEN-LAST:event_jPrebtnMouseMoved

    private void jPrebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPrebtnMouseExited
        // TODO add your handling code here:
        jPrebtn.setBackground(deufault);
    }//GEN-LAST:event_jPrebtnMouseExited

    private void jPrebtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPrebtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPrebtnMouseReleased

    private void jNextbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNextbtnMouseMoved
        // TODO add your handling code here:
        jNextbtn.setBackground(colorMoved);
    }//GEN-LAST:event_jNextbtnMouseMoved

    private void jNextbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNextbtnMouseExited
        // TODO add your handling code here:
        jNextbtn.setBackground(deufault);
    }//GEN-LAST:event_jNextbtnMouseExited

    private void jNextbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNextbtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jNextbtnMouseReleased

    private void jLastbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLastbtnMouseMoved
        // TODO add your handling code here:
        jLastbtn.setBackground(colorMoved);
    }//GEN-LAST:event_jLastbtnMouseMoved

    private void jLastbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLastbtnMouseExited
        // TODO add your handling code here:
        jLastbtn.setBackground(deufault);
    }//GEN-LAST:event_jLastbtnMouseExited

    private void jLastbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLastbtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLastbtnMouseReleased

    private void createViewList() {
        jListConferenceView.add(new ConferenceRenderList(new Conference("C/C++ Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.")));
        jListConferenceView.add(new ConferenceRenderList(new Conference("Java Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.")));
        jListConferenceView.add(new ConferenceRenderList(new Conference("C# Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.")));
        jListConferenceView.add(new ConferenceRenderList(new Conference("IOS Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.")));
        jListConferenceView.add(new ConferenceRenderList(new Conference("Windows Phone Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.E")));
        jListConferenceView.add(new ConferenceRenderList(new Conference("C/C++ Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.A")));
        jListConferenceView.add(new ConferenceRenderList(new Conference("Java Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.B")));
        jListConferenceView.add(new ConferenceRenderList(new Conference("C# Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.C")));
        jListConferenceView.add(new ConferenceRenderList(new Conference("IOS Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.D")));
        jListConferenceView.add(new ConferenceRenderList(new Conference("Windows Phone Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.E")));
        jListConferenceView.add(new ConferenceRenderList(new Conference("C/C++ Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.A")));
        jListConferenceView.add(new ConferenceRenderList(new Conference("Java Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.B")));
        jListConferenceView.add(new ConferenceRenderList(new Conference("C# Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.C")));
        jListConferenceView.add(new ConferenceRenderList(new Conference("IOS Programming", "VLưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.D")));
        jListConferenceView.add(new ConferenceRenderList(new Conference("Windows Phone Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.E")));
    }
    
    private void createViewCard(){
        jCardConferenceView.add(new ConferenceRenderCard(new Conference("C/C++ Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.")));
        jCardConferenceView.add(new ConferenceRenderCard(new Conference("Java Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.")));
        jCardConferenceView.add(new ConferenceRenderCard(new Conference("C# Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.")));
        jCardConferenceView.add(new ConferenceRenderCard(new Conference("IOS Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.")));
        jCardConferenceView.add(new ConferenceRenderCard(new Conference("Windows Phone Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.E")));
        jCardConferenceView.add(new ConferenceRenderCard(new Conference("C/C++ Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.A")));
        jCardConferenceView.add(new ConferenceRenderCard(new Conference("Java Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.B")));
        jCardConferenceView.add(new ConferenceRenderCard(new Conference("C# Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.C")));
        jCardConferenceView.add(new ConferenceRenderCard(new Conference("IOS Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.D")));
        jCardConferenceView.add(new ConferenceRenderCard(new Conference("Windows Phone Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.E")));
        jCardConferenceView.add(new ConferenceRenderCard(new Conference("C/C++ Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.A")));
        jCardConferenceView.add(new ConferenceRenderCard(new Conference("Java Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.B")));
        jCardConferenceView.add(new ConferenceRenderCard(new Conference("C# Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.C")));
        jCardConferenceView.add(new ConferenceRenderCard(new Conference("IOS Programming", "VLưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.D")));
        jCardConferenceView.add(new ConferenceRenderCard(new Conference("Windows Phone Programming", "Lưu ý tham số cuối cùng: nó báo cho bộ thực thi thuật toán bạn muốn sử dụng để thay đổi kích thước.E")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jCardConferenceView;
    private javax.swing.JPanel jCardView;
    private javax.swing.JLabel jCardViewbtn;
    private javax.swing.JPanel jConferenceView;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jFirstbtn;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLastbtn;
    private javax.swing.JPanel jListConferenceView;
    private javax.swing.JPanel jListView;
    private javax.swing.JLabel jListViewbtn;
    private javax.swing.JLabel jNextbtn;
    private javax.swing.JPanel jPaginationConference;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JLabel jPrebtn;
    private javax.swing.JLabel jResetbtn;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel jSearchPnl;
    private javax.swing.JTextField jSearchText;
    private javax.swing.JLabel jSearchbtn;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
