/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ContentUI;

import UserUI.UserButtonEditor;
import UserUI.UserButtonRenderer;
import Class.Conference11;
import java.awt.Color;
import java.awt.Font;
import java.awt.List;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ADMIN
 */
public class Statistic extends javax.swing.JPanel {

    /**
     * Creates new form Statictic
     */
    final static private Color deufault = new Color(224, 224, 250);
    final static private Color colorCliked = new Color(84, 3, 156);
    final static private Color colorMoved = new Color(153, 153, 255);
    final static private Color colorMoved_2 = new Color(220, 220, 255);

    public Statistic()  {

//        try {
            initComponents();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            jTable.getTableHeader().setOpaque(true);
            jTable.getTableHeader().setBackground(Color.red);
            jTable.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 20));
            
            DefaultTableModel tm = (DefaultTableModel) jTable.getModel();
            
//            tm.addRow(new Object[]{1, "A", sdf.parse("11-11-2020"), sdf.parse("11-11-2020"), "Column 4", new Conference11("C#", "1")});
//            tm.addRow(new Object[]{2, "C", sdf.parse("12-11-2020"), sdf.parse("11-11-2020"), "Column 4", new Conference11("JAVA", "2")});
//            tm.addRow(new Object[]{3, "E", sdf.parse("11-11-2020"), sdf.parse("13-11-2016"), "Column 4", new Conference11("PTHON", "3")});
//            tm.addRow(new Object[]{4, "B", sdf.parse("11-11-2020"), sdf.parse("14-11-2015"), "Column 4", new Conference11("TEMP", "4")});
            
            jTable.setModel(tm);
            jTable.getColumnModel().getColumn(5).setCellRenderer(new UserButtonRenderer());
            jTable.getColumnModel().getColumn(5).setCellEditor(new UserButtonEditor(new JTextField()));
            jTable.setAutoCreateRowSorter(true);
//        } catch (ParseException ex) {
//            Logger.getLogger(Statistic.class.getName()).log(Level.SEVERE, null, ex);
//        }



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JPanel();
        jOption = new javax.swing.JPanel();
        jOption1 = new javax.swing.JPanel();
        jResetbtn = new javax.swing.JLabel();
        jFilter = new javax.swing.JPanel();
        jSearchPnl = new javax.swing.JPanel();
        jSearchbtn = new javax.swing.JLabel();
        jSearchText = new javax.swing.JTextField();
        jDate = new javax.swing.JPanel();
        jOrganizedDate = new javax.swing.JPanel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jOrganizedDateText = new javax.swing.JLabel();
        jRegisterdDate = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jRegisteredDateText1 = new javax.swing.JLabel();
        jOption2 = new javax.swing.JPanel();
        jCount = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jBrief = new javax.swing.JLabel();
        jData = new javax.swing.JPanel();
        jPagination = new javax.swing.JPanel();
        jDescriptionPag = new javax.swing.JLabel();
        jPaginationButton = new javax.swing.JPanel();
        jFirstbtn = new javax.swing.JLabel();
        jPrebtn = new javax.swing.JLabel();
        jPosition = new javax.swing.JTextField();
        jNextbtn = new javax.swing.JLabel();
        jLastbtn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jHeader.setBackground(new java.awt.Color(224, 224, 250));
        jHeader.setPreferredSize(new java.awt.Dimension(100, 170));
        jHeader.setLayout(new java.awt.BorderLayout());

        jOption.setBackground(new java.awt.Color(255, 255, 255));
        jOption.setPreferredSize(new java.awt.Dimension(100, 50));
        jOption.setLayout(new java.awt.BorderLayout());

        jOption1.setBackground(new java.awt.Color(224, 224, 250));
        jOption1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jOption1.setMinimumSize(new java.awt.Dimension(100, 50));
        jOption1.setPreferredSize(new java.awt.Dimension(1000, 60));
        jOption1.setLayout(new java.awt.BorderLayout());

        jResetbtn.setBackground(new java.awt.Color(224, 224, 250));
        jResetbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jResetbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Available-Updates-icon.png"))); // NOI18N
        jResetbtn.setOpaque(true);
        jResetbtn.setPreferredSize(new java.awt.Dimension(70, 50));
        jResetbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jResetbtnMouseMoved(evt);
            }
        });
        jResetbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jResetbtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jResetbtnMouseReleased(evt);
            }
        });
        jOption1.add(jResetbtn, java.awt.BorderLayout.WEST);

        jFilter.setBackground(new java.awt.Color(224, 224, 250));
        jFilter.setLayout(new java.awt.BorderLayout());

        jSearchPnl.setBackground(new java.awt.Color(224, 224, 250));
        jSearchPnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        jSearchPnl.setPreferredSize(new java.awt.Dimension(250, 50));
        jSearchPnl.setLayout(new java.awt.BorderLayout());

        jSearchbtn.setBackground(new java.awt.Color(224, 224, 250));
        jSearchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Search-icon.png"))); // NOI18N
        jSearchbtn.setOpaque(true);
        jSearchbtn.setPreferredSize(new java.awt.Dimension(50, 13));
        jSearchbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jSearchbtnMouseMoved(evt);
            }
        });
        jSearchbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jSearchbtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSearchbtnMouseReleased(evt);
            }
        });
        jSearchPnl.add(jSearchbtn, java.awt.BorderLayout.WEST);

        jSearchText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jSearchText.setText("Search conference name");
        jSearchText.setToolTipText("");
        jSearchText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jSearchText.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jSearchText.setPreferredSize(new java.awt.Dimension(200, 27));
        jSearchText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSearchTextFocusLost(evt);
            }
        });
        jSearchPnl.add(jSearchText, java.awt.BorderLayout.CENTER);

        jFilter.add(jSearchPnl, java.awt.BorderLayout.CENTER);

        jDate.setPreferredSize(new java.awt.Dimension(650, 100));
        jDate.setLayout(new java.awt.BorderLayout());

        jOrganizedDate.setBackground(new java.awt.Color(224, 224, 250));
        jOrganizedDate.setPreferredSize(new java.awt.Dimension(275, 50));
        jOrganizedDate.setLayout(new java.awt.BorderLayout());

        jDateChooser.setDateFormatString("dd/MM/yyyy");
        jDateChooser.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jDateChooser.setOpaque(false);
        jDateChooser.setPreferredSize(new java.awt.Dimension(75, 50));
        jOrganizedDate.add(jDateChooser, java.awt.BorderLayout.CENTER);

        jOrganizedDateText.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jOrganizedDateText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jOrganizedDateText.setText("Organized Date");
        jOrganizedDateText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jOrganizedDateText.setPreferredSize(new java.awt.Dimension(150, 50));
        jOrganizedDate.add(jOrganizedDateText, java.awt.BorderLayout.WEST);

        jDate.add(jOrganizedDate, java.awt.BorderLayout.CENTER);

        jRegisterdDate.setBackground(new java.awt.Color(224, 224, 250));
        jRegisterdDate.setMinimumSize(new java.awt.Dimension(125, 27));
        jRegisterdDate.setPreferredSize(new java.awt.Dimension(325, 50));
        jRegisterdDate.setLayout(new java.awt.BorderLayout());

        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jDateChooser1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jDateChooser1.setOpaque(false);
        jDateChooser1.setPreferredSize(new java.awt.Dimension(75, 50));
        jRegisterdDate.add(jDateChooser1, java.awt.BorderLayout.CENTER);

        jRegisteredDateText1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRegisteredDateText1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jRegisteredDateText1.setText("Registered Date");
        jRegisteredDateText1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jRegisteredDateText1.setPreferredSize(new java.awt.Dimension(150, 50));
        jRegisterdDate.add(jRegisteredDateText1, java.awt.BorderLayout.WEST);

        jDate.add(jRegisterdDate, java.awt.BorderLayout.WEST);

        jFilter.add(jDate, java.awt.BorderLayout.WEST);

        jOption1.add(jFilter, java.awt.BorderLayout.CENTER);

        jOption.add(jOption1, java.awt.BorderLayout.NORTH);

        jOption2.setBackground(new java.awt.Color(224, 224, 250));
        jOption2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jOption2.setLayout(new java.awt.BorderLayout());

        jCount.setPreferredSize(new java.awt.Dimension(220, 0));
        jCount.setLayout(new java.awt.BorderLayout());

        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(70, 50));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jCount.add(jComboBox1, java.awt.BorderLayout.EAST);

        jLabel1.setBackground(new java.awt.Color(224, 224, 250));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Number of lines ");
        jLabel1.setOpaque(true);
        jCount.add(jLabel1, java.awt.BorderLayout.CENTER);

        jOption2.add(jCount, java.awt.BorderLayout.WEST);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete");
        jButton1.setBorderPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(100, 21));
        jOption2.add(jButton1, java.awt.BorderLayout.EAST);

        jOption.add(jOption2, java.awt.BorderLayout.CENTER);

        jHeader.add(jOption, java.awt.BorderLayout.CENTER);

        jBrief.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jBrief.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBrief.setText("List of registered conferences");
        jBrief.setPreferredSize(new java.awt.Dimension(78, 55));
        jHeader.add(jBrief, java.awt.BorderLayout.NORTH);

        add(jHeader, java.awt.BorderLayout.NORTH);

        jData.setBackground(new java.awt.Color(255, 102, 51));
        jData.setOpaque(false);
        jData.setLayout(new java.awt.BorderLayout());

        jPagination.setBackground(new java.awt.Color(224, 224, 250));
        jPagination.setPreferredSize(new java.awt.Dimension(1000, 50));
        jPagination.setLayout(new java.awt.BorderLayout());

        jDescriptionPag.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jDescriptionPag.setText("Page 1 for 1-6/100");
        jDescriptionPag.setPreferredSize(new java.awt.Dimension(300, 13));
        jPagination.add(jDescriptionPag, java.awt.BorderLayout.WEST);

        jPaginationButton.setOpaque(false);
        jPaginationButton.setPreferredSize(new java.awt.Dimension(290, 50));
        jPaginationButton.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jFirstbtn.setBackground(new java.awt.Color(224, 224, 250));
        jFirstbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFirstbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Rewind-icon.png"))); // NOI18N
        jFirstbtn.setOpaque(true);
        jFirstbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jFirstbtnMouseMoved(evt);
            }
        });
        jFirstbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jFirstbtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jFirstbtnMouseReleased(evt);
            }
        });
        jPaginationButton.add(jFirstbtn);

        jPrebtn.setBackground(new java.awt.Color(224, 224, 250));
        jPrebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPrebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Chevron-Left-icon.png"))); // NOI18N
        jPrebtn.setOpaque(true);
        jPrebtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPrebtnMouseMoved(evt);
            }
        });
        jPrebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPrebtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPrebtnMouseReleased(evt);
            }
        });
        jPaginationButton.add(jPrebtn);

        jPosition.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPaginationButton.add(jPosition);

        jNextbtn.setBackground(new java.awt.Color(224, 224, 250));
        jNextbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNextbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Chevron-Right-icon.png"))); // NOI18N
        jNextbtn.setOpaque(true);
        jNextbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jNextbtnMouseMoved(evt);
            }
        });
        jNextbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jNextbtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jNextbtnMouseReleased(evt);
            }
        });
        jPaginationButton.add(jNextbtn);

        jLastbtn.setBackground(new java.awt.Color(224, 224, 250));
        jLastbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLastbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Fast-Forward-icon.png"))); // NOI18N
        jLastbtn.setOpaque(true);
        jLastbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLastbtnMouseMoved(evt);
            }
        });
        jLastbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLastbtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLastbtnMouseReleased(evt);
            }
        });
        jPaginationButton.add(jLastbtn);

        jPagination.add(jPaginationButton, java.awt.BorderLayout.EAST);

        jData.add(jPagination, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setOpaque(false);

        jTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        DefaultTableModel tm = new DefaultTableModel(new Object[0][], new String[]{"STT", "Conference Name", "Registered Date", "Organized Date", "Status", "Detail"}) {
            @Override
            public Class<?> getColumnClass(int col) {
                //here it really returns the right column class (Integer.class)
                Class retVal = Object.class;

                if(getRowCount() == 2 || getRowCount() == 3)
                return Date.class;

                if (getRowCount() > 0) {
                    retVal = getValueAt(0, col).getClass();
                }

                return retVal;
            }

        };
        jTable.setModel(tm);
        jTable.setFocusable(false);
        jTable.setGridColor(new java.awt.Color(153, 153, 255));
        jTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable.setRowHeight(50);
        jTable.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jTable.setShowGrid(true);
        jTable.setShowVerticalLines(false);
        jTable.getTableHeader().setResizingAllowed(false);
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable);

        jData.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jData, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jResetbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jResetbtnMouseMoved
        // TODO add your handling code here:
        jResetbtn.setBackground(colorMoved);
    }//GEN-LAST:event_jResetbtnMouseMoved

    private void jResetbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jResetbtnMouseExited
        // TODO add your handling code here:
        jResetbtn.setBackground(deufault);
    }//GEN-LAST:event_jResetbtnMouseExited

    private void jResetbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jResetbtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jResetbtnMouseReleased

    private void jSearchbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchbtnMouseMoved
        // TODO add your handling code here:
        jSearchbtn.setBackground(colorMoved);
    }//GEN-LAST:event_jSearchbtnMouseMoved

    private void jSearchbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchbtnMouseExited
        // TODO add your handling code here:
        jSearchbtn.setBackground(deufault);
    }//GEN-LAST:event_jSearchbtnMouseExited

    private void jSearchbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchbtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchbtnMouseReleased

    private void jSearchTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSearchTextFocusLost
        // TODO add your handling code here:
        if (jSearchText.getText().compareTo("") == 0)
            jSearchText.setText("Search conference name ");
    }//GEN-LAST:event_jSearchTextFocusLost

    private void jFirstbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFirstbtnMouseMoved
        // TODO add your handling code here:
        jFirstbtn.setBackground(colorMoved);
    }//GEN-LAST:event_jFirstbtnMouseMoved

    private void jFirstbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFirstbtnMouseExited
        // TODO add your handling code here:
        jFirstbtn.setBackground(deufault);
    }//GEN-LAST:event_jFirstbtnMouseExited

    private void jFirstbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFirstbtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jFirstbtnMouseReleased

    private void jPrebtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPrebtnMouseMoved
        // TODO add your handling code here:
        jPrebtn.setBackground(colorMoved);
    }//GEN-LAST:event_jPrebtnMouseMoved

    private void jPrebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPrebtnMouseExited
        // TODO add your handling code here:
        jPrebtn.setBackground(deufault);
    }//GEN-LAST:event_jPrebtnMouseExited

    private void jPrebtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPrebtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPrebtnMouseReleased

    private void jNextbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNextbtnMouseMoved
        // TODO add your handling code here:
        jNextbtn.setBackground(colorMoved);
    }//GEN-LAST:event_jNextbtnMouseMoved

    private void jNextbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNextbtnMouseExited
        // TODO add your handling code here:
        jNextbtn.setBackground(deufault);
    }//GEN-LAST:event_jNextbtnMouseExited

    private void jNextbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNextbtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jNextbtnMouseReleased

    private void jLastbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLastbtnMouseMoved
        // TODO add your handling code here:
        jLastbtn.setBackground(colorMoved);
    }//GEN-LAST:event_jLastbtnMouseMoved

    private void jLastbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLastbtnMouseExited
        // TODO add your handling code here:
        jLastbtn.setBackground(deufault);
    }//GEN-LAST:event_jLastbtnMouseExited

    private void jLastbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLastbtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLastbtnMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBrief;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jCount;
    private javax.swing.JPanel jData;
    private javax.swing.JPanel jDate;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jDescriptionPag;
    private javax.swing.JPanel jFilter;
    private javax.swing.JLabel jFirstbtn;
    private javax.swing.JPanel jHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLastbtn;
    private javax.swing.JLabel jNextbtn;
    private javax.swing.JPanel jOption;
    private javax.swing.JPanel jOption1;
    private javax.swing.JPanel jOption2;
    private javax.swing.JPanel jOrganizedDate;
    private javax.swing.JLabel jOrganizedDateText;
    private javax.swing.JPanel jPagination;
    private javax.swing.JPanel jPaginationButton;
    private javax.swing.JTextField jPosition;
    private javax.swing.JLabel jPrebtn;
    private javax.swing.JPanel jRegisterdDate;
    private javax.swing.JLabel jRegisteredDateText1;
    private javax.swing.JLabel jResetbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jSearchPnl;
    private javax.swing.JTextField jSearchText;
    private javax.swing.JLabel jSearchbtn;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
