/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ContentUI;

import Business.AccountBus;
import Business.UserBus;
import POJO.Account;
import POJO.User;
import javax.swing.JOptionPane;
import MainScreenUI.MainScreen;
/**
 *
 * @author ADMIN
 */
public class UserInformation extends javax.swing.JPanel {

    /**
     * Creates new form Information
     */
    private User user;
    private boolean editInformation = false;
    private boolean changePassword = false;

    public UserInformation() {
        initComponents();

        
    }
    
    public void init(){
        jCancelbtn.setVisible(false);
        jNameTF.setText(user.getName());
        jEmailTF.setText(user.getEmail());

        jCancelbtn1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jNameTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jEmailTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCancelbtn = new javax.swing.JButton();
        jEditbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jCancelbtn1 = new javax.swing.JButton();
        jChangebtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jOldPasswordTF = new javax.swing.JPasswordField();
        jNewPasswordTF = new javax.swing.JPasswordField();
        jConfirmPasswordTF = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(224, 224, 250));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(224, 224, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 250));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Name");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel1.add(jLabel1, gridBagConstraints);

        jNameTF.setEditable(false);
        jNameTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jNameTF.setPreferredSize(new java.awt.Dimension(850, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel1.add(jNameTF, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Email");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel1.add(jLabel2, gridBagConstraints);

        jEmailTF.setEditable(false);
        jEmailTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jEmailTF.setPreferredSize(new java.awt.Dimension(850, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel1.add(jEmailTF, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Information");
        jLabel3.setPreferredSize(new java.awt.Dimension(1000, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jLabel3, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(224, 224, 250));
        jPanel3.setPreferredSize(new java.awt.Dimension(850, 50));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jCancelbtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jCancelbtn.setText("Cancel");
        jCancelbtn.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel3.add(jCancelbtn);

        jEditbtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jEditbtn.setText("Edit");
        jEditbtn.setPreferredSize(new java.awt.Dimension(100, 40));
        jEditbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jEditbtnMousePressed(evt);
            }
        });
        jPanel3.add(jEditbtn);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jPanel3, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(224, 224, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 300));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Old Password");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("New Password");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Change Password");
        jLabel6.setPreferredSize(new java.awt.Dimension(1000, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel2.add(jLabel6, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(224, 224, 250));
        jPanel4.setPreferredSize(new java.awt.Dimension(850, 50));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jCancelbtn1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jCancelbtn1.setText("Cancel");
        jCancelbtn1.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel4.add(jCancelbtn1);

        jChangebtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jChangebtn.setText("Change");
        jChangebtn.setPreferredSize(new java.awt.Dimension(100, 40));
        jChangebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jChangebtnMouseReleased(evt);
            }
        });
        jPanel4.add(jChangebtn);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel2.add(jPanel4, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Confirm Password");
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        jPanel2.add(jLabel7, gridBagConstraints);

        jOldPasswordTF.setEditable(false);
        jOldPasswordTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jOldPasswordTF.setPreferredSize(new java.awt.Dimension(850, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel2.add(jOldPasswordTF, gridBagConstraints);

        jNewPasswordTF.setEditable(false);
        jNewPasswordTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jNewPasswordTF.setPreferredSize(new java.awt.Dimension(850, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel2.add(jNewPasswordTF, gridBagConstraints);

        jConfirmPasswordTF.setEditable(false);
        jConfirmPasswordTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jConfirmPasswordTF.setPreferredSize(new java.awt.Dimension(850, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        jPanel2.add(jConfirmPasswordTF, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jEditbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditbtnMousePressed
        // TODO add your handling code here:
        if (editInformation == false) {
            editInformation = true;
            jEditbtn.setText("OK");
            jCancelbtn.setVisible(true);
            jNameTF.setEditable(true);
            jEmailTF.setEditable(true);
        } else {
            editInformation = false;
            user.setName(jNameTF.getText());
            user.setEmail(jEmailTF.getText());
            UserBus.updateUserInformation(user);
            jEditbtn.setText("Edit");
            jCancelbtn.setVisible(false);
        }

    }//GEN-LAST:event_jEditbtnMousePressed

    private void jChangebtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChangebtnMouseReleased
        // TODO add your handling code here:
        if (changePassword == false) {
            changePassword = true;
            jChangebtn.setText("OK");
            jCancelbtn1.setVisible(true);
            jOldPasswordTF.setEditable(true);
            jNewPasswordTF.setEditable(true);
            jConfirmPasswordTF.setEditable(true);
        } else {

            if (AccountBus.checkAccount(user.getAccount().getUserName(), jOldPasswordTF.getText()) != 1) {
                JOptionPane.showMessageDialog(this, "Old password is not correct");
                return;
            }

            if (jNewPasswordTF.getText().compareTo(jConfirmPasswordTF.getText()) != 0) {
                JOptionPane.showMessageDialog(this, "New passwords are not match");
                return;
            }
            
            boolean result = AccountBus.changePassword(user.getAccount().getUserName(), jNewPasswordTF.getText());
            
            if(result)
                JOptionPane.showMessageDialog(this, "Success");
            else
                JOptionPane.showMessageDialog(this, "fail");
            
            jChangebtn.setText("Change");
            jCancelbtn1.setVisible(false);
            jOldPasswordTF.setEditable(true);
            jNewPasswordTF.setEditable(true);
            jConfirmPasswordTF.setEditable(true);
            jOldPasswordTF.setText("");
            jNewPasswordTF.setText("");
            jConfirmPasswordTF.setText("");
            editInformation = false;

        }
    }//GEN-LAST:event_jChangebtnMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelbtn;
    private javax.swing.JButton jCancelbtn1;
    private javax.swing.JButton jChangebtn;
    private javax.swing.JPasswordField jConfirmPasswordTF;
    private javax.swing.JButton jEditbtn;
    private javax.swing.JTextField jEmailTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNameTF;
    private javax.swing.JPasswordField jNewPasswordTF;
    private javax.swing.JPasswordField jOldPasswordTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
