/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminUI;

import MainScreenUI.MainScreen;
import Business.UserConferenceBus;
import POJO.User;
import POJO.UserConference;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class ListConferenceUserDialog extends java.awt.Dialog {

    /**
     * Creates new form ListConferenceUserDialog
     */
    private User user;
    private List<UserConference> list;

    public ListConferenceUserDialog(java.awt.Frame parent, boolean modal, User user) {
        super(parent, modal);
        initComponents();
        this.user = user;
        this.setLocationRelativeTo(parent);

        jNameTF.setText(user.getName());
        jEmailTF.setText(user.getEmail());

        list = UserConferenceBus.getListUserConferenceByUser(user);

        DefaultTableModel tm = (DefaultTableModel) jTable.getModel();

        for (int i = 0; i < list.size(); i++) {

            String status;

            if (list.get(i).getIsAccepted() == 0) {
                status = "No Accepted yet";
            } else if (list.get(i).getIsAccepted() == 1) {
                status = "Accepted";
            } else {
                status = "Denied";
            }

            tm.addRow(new Object[]{i + 1, list.get(i).getConference().getName(), list.get(i).getConference().getPlace().getName(), list.get(i).getConference().getPlace().getAddress()});

        }

        jTable.setModel(tm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jNameTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jEmailTF = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(800, 560));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel6.setLayout(new java.awt.BorderLayout());

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Conference Name", "Place", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel7.setPreferredSize(new java.awt.Dimension(10, 100));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Name");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel7.add(jLabel1, new java.awt.GridBagConstraints());

        jNameTF.setEditable(false);
        jNameTF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jNameTF.setText("jTextField1");
        jNameTF.setPreferredSize(new java.awt.Dimension(680, 40));
        jNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameTFActionPerformed(evt);
            }
        });
        jPanel7.add(jNameTF, new java.awt.GridBagConstraints());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Email");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel7.add(jLabel2, gridBagConstraints);

        jEmailTF.setEditable(false);
        jEmailTF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jEmailTF.setText("jTextField2");
        jEmailTF.setPreferredSize(new java.awt.Dimension(680, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel7.add(jEmailTF, gridBagConstraints);

        add(jPanel7, java.awt.BorderLayout.NORTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameTFActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jEmailTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jNameTF;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
